import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ArrowLeft, ArrowRight, KeyRound, LockKeyhole, Mail, ShieldCheck, UserRound, WalletCards } from "lucide-react";
import { useEffect } from "react";
import { Link, useLocation } from "wouter";

function AccountBenefits() {
  return <div className="customer-auth-copy"><span>VAMNUX / ACCOUNT ACCESS</span><h1>Your digital<br /><em>space.</em></h1><p>Use a protected account to access your wallet, saved products, private support tickets, account settings, and future wallet-only purchases.</p><div><span><ShieldCheck size={17} /> Account-scoped data</span><span><WalletCards size={17} /> Wallet-only purchase policy</span><span><LockKeyhole size={17} /> Server-authorised operations</span></div></div>;
}

function SecureSignIn() {
  const [, setLocation] = useLocation();
  return <div className="customer-auth-card"><LockKeyhole size={24} /><p>SECURE SIGN IN</p><h2>Access your<br />VAMNUX account.</h2><span>Continue through VAMNUX’s configured secure identity provider to enter your account. Your email and password are handled by that protected service, not collected by this page.</span><div className="grid w-full gap-3 border border-white/10 bg-white/5 p-3 text-[10px] text-slate-300"><div className="flex gap-2"><Mail className="mt-0.5 shrink-0 text-[#b8ff43]" size={15} /><p><strong className="block text-[10px] uppercase tracking-[.06em] text-white">Email and password</strong>Enter credentials only in the configured secure sign-in window.</p></div><div className="flex gap-2"><ShieldCheck className="mt-0.5 shrink-0 text-[#b8ff43]" size={15} /><p><strong className="block text-[10px] uppercase tracking-[.06em] text-white">Human verification</strong>Verified by the identity provider where enabled; no simulated CAPTCHA is shown here.</p></div></div><div className="customer-auth-choices"><button type="button" onClick={() => startLogin()} className="user-primary-action">Continue to secure sign in <ArrowRight size={15} /></button><button type="button" onClick={() => setLocation("/login?mode=signup")} className="user-secondary-action">Create secure account <UserRound size={15} /></button></div><small>Forgot-password and email verification are provided only through configured identity and email services. VAMNUX does not imitate these security checks locally.</small></div>;
}

function RegistrationReadiness() {
  const [, setLocation] = useLocation();
  const fields = [["First name", "Your first name"], ["Last name", "Your last name"], ["Email address", "name@example.com"], ["Phone number · optional", "Optional contact number"], ["Country", "Select your country"], ["How did you hear about us?", "Optional referral source"]] as const;
  return <div className="customer-auth-card"><UserRound size={24} /><p>CREATE SECURE ACCOUNT</p><h2>Set up your<br />VAMNUX profile.</h2><span>After secure account creation, complete these details in your VAMNUX profile. This page shows the information VAMNUX needs without storing a password or pretending that verification is complete.</span><div className="grid w-full gap-2 sm:grid-cols-2">{fields.map(([label, placeholder]) => <label key={label} className="grid gap-1 text-[8px] font-extrabold uppercase tracking-[.07em] text-slate-300"><span>{label}</span><input disabled placeholder={placeholder} className="h-9 border border-white/15 bg-[#0b0f18] px-2 text-[9px] text-slate-400 opacity-100" /></label>)}</div><section className="mt-3 w-full border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2"><KeyRound className="text-[#b8ff43]" size={15} /><strong className="text-[9px] uppercase tracking-[.07em] text-white">Password requirements</strong></div><p className="mt-2 text-[9px] leading-4 text-slate-300">Use at least 12 characters with uppercase and lowercase letters, a number, and a symbol. Confirm the same password before continuing in the secure identity service.</p><div className="mt-2 grid grid-cols-4 gap-1 text-center text-[7px] text-slate-400"><span className="border-t-2 border-slate-600 pt-1">Weak</span><span className="border-t-2 border-slate-600 pt-1">Medium</span><span className="border-t-2 border-slate-600 pt-1">Strong</span><span className="border-t-2 border-slate-600 pt-1">Excellent</span></div><small className="mt-2 block text-[8px] leading-3 text-slate-400">Password strength and confirmation are evaluated only by the configured identity service, which is not yet active for native VAMNUX passwords.</small></section><section className="mt-2 flex w-full gap-2 border border-white/10 bg-white/5 p-3 text-[9px] leading-4 text-slate-300"><ShieldCheck className="shrink-0 text-[#b8ff43]" size={16} /><p><strong className="text-white">Email verification &amp; human verification.</strong> These steps activate only when VAMNUX configures verified identity, CAPTCHA, and transactional-email services. No local checkbox can verify a person or an email address.</p></section><div className="customer-auth-choices"><button type="button" onClick={() => startLogin()} className="user-primary-action">Continue with secure sign in <ArrowRight size={15} /></button><button type="button" onClick={() => setLocation("/login")} className="user-secondary-action"><ArrowLeft size={15} /> Back to sign in</button></div><small>Do not enter supplier, wallet, payment, or recovery credentials into VAMNUX profile fields.</small></div>;
}

export default function CustomerAuth() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const registrationMode = new URLSearchParams(window.location.search).get("mode") === "signup";
  useEffect(() => { if (!loading && user) setLocation("/account"); }, [loading, setLocation, user]);
  if (!loading && user) return null;
  return <main className="customer-auth-page"><header><Link href="/" className="user-brand"><span>V</span>VAM<em>NUX</em></Link><Link href="/">Return to marketplace</Link></header><section><AccountBenefits />{registrationMode ? <RegistrationReadiness /> : <SecureSignIn />}</section></main>;
}
