import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Bell, BookOpen, CheckCircle2, ChevronRight, CircleAlert, CircleHelp, Clock3, Coins, FolderOpen, Gamepad2, Gift, Heart, KeyRound, LayoutDashboard, LockKeyhole, LogOut, MailCheck, Package, ReceiptText, RefreshCw, Settings2, ShieldCheck, Sparkles, Star, Ticket, Tv, UserRound, WalletCards } from "lucide-react";
import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

type DashboardTab = "overview" | "orders" | "wallet" | "catalogs" | "transactions" | "favorites" | "buyAgain" | "rewards" | "referrals" | "subscriptions" | "notifications" | "support" | "profile" | "security" | "settings" | "privacy";
type SupportCategory = "payment" | "order" | "game_top_up" | "gift_card" | "subscription" | "software" | "wallet" | "account" | "refund" | "other";

const navigationGroups: Array<{ label: string; items: Array<{ id: DashboardTab; label: string; icon: typeof LayoutDashboard }> }> = [
  { label: "Account", items: [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "orders", label: "My orders", icon: Package }, { id: "wallet", label: "Wallet", icon: WalletCards }, { id: "transactions", label: "Transactions", icon: ReceiptText }] },
  { label: "Discover", items: [{ id: "catalogs", label: "Catalogs", icon: FolderOpen }, { id: "favorites", label: "Favorites", icon: Heart }, { id: "buyAgain", label: "Buy again", icon: RefreshCw }, { id: "subscriptions", label: "Subscriptions", icon: Tv }] },
  { label: "Benefits", items: [{ id: "rewards", label: "Rewards & loyalty", icon: Star }, { id: "referrals", label: "Referrals", icon: Gift }] },
  { label: "Help & settings", items: [{ id: "notifications", label: "Notifications", icon: Bell }, { id: "support", label: "Support", icon: CircleHelp }, { id: "profile", label: "Profile", icon: UserRound }, { id: "security", label: "Security", icon: LockKeyhole }, { id: "settings", label: "Settings", icon: Settings2 }, { id: "privacy", label: "Privacy", icon: ShieldCheck }] },
];

const catalogLinks = [
  { label: "Game top-up", filter: "Top-up", icon: Coins, detail: "Game credits, diamonds, UC, passes and more" },
  { label: "Gift cards", filter: "Voucher", icon: Gift, detail: "Digital vouchers and codes when available" },
  { label: "Subscriptions", filter: "Subscription", icon: Tv, detail: "Entertainment and premium digital services" },
  { label: "Software", filter: "Software", icon: BookOpen, detail: "Software licences and productivity tools" },
  { label: "AI tools", filter: "AI tools", icon: Sparkles, detail: "AI subscriptions and digital tools" },
  { label: "Steam", filter: "Steam", icon: Gamepad2, detail: "Steam wallet and game offers" },
  { label: "Telegram Stars", filter: "Telegram Stars", icon: Star, detail: "Telegram Stars offers and denominations" },
];

function money(amount: string | number, currency: string) { return new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(amount)); }
function label(value: string) { return value.replaceAll("_", " "); }
function Empty({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="account-hub-empty"><Package size={22} /><h3>{title}</h3><p>{detail}</p>{action}</div>; }
function Inactive({ title, detail }: { title: string; detail: string }) { return <div className="account-hub-inactive"><Clock3 size={19} /><div><strong>{title}</strong><p>{detail}</p></div><span>Not active</span></div>; }

export default function UserDashboard() {
  const { user, loading, logout } = useAuth();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const [tab, setTab] = useState<DashboardTab>("overview");
  const [orderCode, setOrderCode] = useState<string | null>(null);
  const [topUpAmount, setTopUpAmount] = useState("");
  const [topUpNote, setTopUpNote] = useState("");
  const [profile, setProfile] = useState({ firstName: "", lastName: "", username: "", phone: "", countryCode: "" });
  const [currency, setCurrency] = useState("USD");
  const dashboard = trpc.marketplace.customerDashboard.useQuery(undefined, { enabled: Boolean(user) });
  const orderDetail = trpc.marketplace.orderDetail.useQuery({ orderCode: orderCode || "" }, { enabled: Boolean(orderCode) });
  const invalidate = () => utils.marketplace.customerDashboard.invalidate();
  const fundWallet = trpc.marketplace.createWalletFundingRequest.useMutation({ onSuccess: async (result) => { toast.success(`Top-up request ${result.fundingCode} submitted for authorised review.`); setTopUpAmount(""); setTopUpNote(""); await invalidate(); }, onError: (error) => toast.error(error.message || "We could not submit the top-up request.") });
  const saveProduct = trpc.marketplace.toggleSavedProduct.useMutation({ onSuccess: invalidate, onError: (error) => toast.error(error.message || "We could not update your favorites.") });
  const markRead = trpc.marketplace.markNotificationRead.useMutation({ onSuccess: invalidate });
  const saveProfile = trpc.marketplace.updateCustomerProfile.useMutation({ onSuccess: async () => { toast.success("Your VAMNUX profile was saved."); await invalidate(); }, onError: (error) => toast.error(error.message || "We could not save your profile.") });
  const savePreferences = trpc.marketplace.updateCustomerPreferences.useMutation({ onSuccess: async () => { toast.success("Your preferences were saved."); await invalidate(); }, onError: (error) => toast.error(error.message || "We could not save your preferences.") });
  const saveNotifications = trpc.marketplace.updateNotificationPreferences.useMutation({ onSuccess: async () => { toast.success("Notification preferences saved."); await invalidate(); } });
  const createTicket = trpc.marketplace.createSupportTicket.useMutation({ onSuccess: async () => { toast.success("Your support ticket was submitted."); await invalidate(); }, onError: (error) => toast.error(error.message || "We could not submit that ticket.") });
  const createPrivacyRequest = trpc.marketplace.createPrivacyRequest.useMutation({ onSuccess: async (result) => { toast.success(`Privacy request ${result.requestCode} submitted for review.`); await invalidate(); } });
  const logoutAll = trpc.auth.logoutAllNativeSessions.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); setLocation("/login"); }, onError: () => toast.error("We could not sign out native password sessions from this screen.") });

  useEffect(() => {
    const item = dashboard.data?.profile;
    if (!item) return;
    setProfile({ firstName: item.firstName || "", lastName: item.lastName || "", username: item.username || "", phone: item.phone || "", countryCode: item.countryCode || "" });
    setCurrency(item.preferredCurrency || "USD");
  }, [dashboard.data?.profile]);

  const orders = dashboard.data?.orders ?? [];
  const displayName = [dashboard.data?.profile?.firstName, dashboard.data?.profile?.lastName].filter(Boolean).join(" ") || user?.name || "VAMNUX customer";
  const orderStats = useMemo(() => ({ total: orders.length, active: orders.filter((item) => ["pending_payment", "paid", "processing"].includes(item.status)).length, delivered: orders.filter((item) => item.status === "delivered").length }), [orders]);
  const isNative = user?.loginMethod === "native_email";

  if (loading || dashboard.isLoading) return <main className="account-hub-loading"><span>V</span><p>Loading your VAMNUX workspace…</p></main>;
  if (!user) return <main className="account-hub-loading"><span>V</span><h1>Your VAMNUX account</h1><p>Sign in to see your wallet, orders, favorites and account settings.</p><Link href="/login" className="account-hub-primary">Sign in <ArrowRight size={16} /></Link></main>;
  if (!dashboard.data) return <main className="account-hub-loading"><CircleAlert size={26} /><h1>Your VAMNUX dashboard is unavailable</h1><p>No account data has been changed. Please retry the protected account request.</p><button className="account-hub-primary" onClick={() => void dashboard.refetch()}>Retry <RefreshCw size={16} /></button></main>;
  const data = dashboard.data;

  const submitTopUp = (event: FormEvent) => { event.preventDefault(); const amount = Number(topUpAmount); if (!Number.isFinite(amount) || amount <= 0 || amount > 1_000_000) return toast.error("Enter an amount between 0.01 and 1,000,000."); fundWallet.mutate({ amount, currency: data.wallet.currency as "USD" | "EUR" | "GBP" | "NGN", customerNote: topUpNote.trim() || undefined }); };
  const submitProfile = (event: FormEvent) => { event.preventDefault(); if (!profile.firstName.trim() || !profile.lastName.trim()) return toast.error("Enter your first and last name."); saveProfile.mutate({ firstName: profile.firstName.trim(), lastName: profile.lastName.trim(), username: profile.username.trim() || null, phone: profile.phone.trim() || null, countryCode: profile.countryCode.trim().toUpperCase() || null }); };
  const submitSettings = (event: FormEvent) => { event.preventDefault(); savePreferences.mutate({ preferredCurrency: currency as "USD" | "EUR" | "GBP" | "NGN", countryCode: profile.countryCode.trim().toUpperCase() || null }); };
  const submitTicket = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); createTicket.mutate({ category: form.get("category") as SupportCategory, subject: String(form.get("subject") || ""), message: String(form.get("message") || ""), orderCode: String(form.get("orderCode") || "") || undefined }); };

  const render = () => {
    if (tab === "overview") return <><section className="account-hub-welcome"><div><span>VAMNUX / PRIVATE WORKSPACE</span><h1>Welcome <em>{displayName}</em></h1><p>Manage your wallet, orders, saved digital products, support, and account controls from one secure place.</p></div><div className="account-hub-welcome-actions"><button onClick={() => setTab("wallet")} className="account-hub-primary"><WalletCards size={16} /> Fund wallet</button><button onClick={() => setTab("catalogs")} className="account-hub-secondary">Browse catalog <ArrowRight size={15} /></button></div></section><section className="account-hub-summary"><article className="balance"><span>AVAILABLE BALANCE</span><strong>{money(data.wallet.availableBalance, data.wallet.currency)}</strong><small>{data.wallet.status} wallet · {data.wallet.currency}</small><button onClick={() => setTab("wallet")}>Manage wallet <ArrowRight size={14} /></button></article><article><Package size={20} /><strong>{orderStats.total}</strong><span>Total orders</span></article><article><CheckCircle2 size={20} /><strong>{orderStats.delivered}</strong><span>Completed</span></article><article><Star size={20} /><strong>—</strong><span>Rewards</span><small>Not active</small></article></section><section className="account-hub-grid"><div className="account-hub-panel"><header><div><span>QUICK ACTIONS</span><h2>What do you need?</h2></div></header><div className="account-hub-quick-list"><button onClick={() => setTab("catalogs")}><FolderOpen size={18} /><span><b>Browse digital catalogs</b><small>Find game top-ups, Steam, gift cards and more.</small></span><ArrowRight size={16} /></button><button onClick={() => setTab("orders")}><Package size={18} /><span><b>Track an order</b><small>View your actual VAMNUX order status.</small></span><ArrowRight size={16} /></button><button onClick={() => setTab("support")}><CircleHelp size={18} /><span><b>Get support</b><small>Open a private customer-service ticket.</small></span><ArrowRight size={16} /></button></div></div><div className="account-hub-panel"><header><div><span>RECENT ORDERS</span><h2>Order activity</h2></div><button onClick={() => setTab("orders")}>View all <ArrowRight size={14} /></button></header>{orders.length ? <div className="account-hub-list">{orders.slice(0, 4).map((order) => <button key={order.orderCode} onClick={() => { setOrderCode(order.orderCode); setTab("orders"); }}><span><b>{order.orderCode}</b><small>{new Date(order.createdAt).toLocaleString()}</small></span><em>{label(order.status)}</em><strong>{money(order.total, order.currency)}</strong><ChevronRight size={16} /></button>)}</div> : <Empty title="No orders yet" detail="Browse the catalog when you are ready; your real VAMNUX orders will appear here." action={<button className="account-hub-link" onClick={() => setTab("catalogs")}>Browse catalog</button>} />}</div></section></>;
    if (tab === "catalogs") return <section className="account-hub-panel"><header><div><span>VAMNUX CATALOGS</span><h2>Find what you need</h2><p>Choose a category to open the matching VAMNUX marketplace view.</p></div></header><div className="account-hub-catalog-grid">{catalogLinks.map((item) => { const Icon = item.icon; return <Link key={item.filter} href={`/?category=${encodeURIComponent(item.filter)}`}><Icon size={20} /><span><b>{item.label}</b><small>{item.detail}</small></span><ArrowRight size={16} /></Link>; })}</div></section>;
    if (tab === "orders") return <section className="account-hub-panel"><header><div><span>MY ORDERS</span><h2>History & tracking</h2><p>Only real orders created with your VAMNUX account appear here.</p></div></header>{orders.length ? <><div className="account-hub-list">{orders.map((order) => <button key={order.orderCode} onClick={() => setOrderCode(order.orderCode)}><span><b>{order.orderCode}</b><small>{new Date(order.createdAt).toLocaleString()}</small></span><em>{label(order.status)}</em><strong>{money(order.total, order.currency)}</strong><ChevronRight size={16} /></button>)}</div>{orderCode && <div className="account-hub-detail">{orderDetail.isLoading ? <p>Loading private order tracking…</p> : orderDetail.data ? <><b>{orderCode}</b><div><span>Order: {label(orderDetail.data.order.status)}</span><span>Payment: {label(orderDetail.data.order.paymentStatus)}</span><span>Supplier: {label(orderDetail.data.order.supplierStatus)}</span></div>{orderDetail.data.items.map((item, index) => <p key={`${item.productName}-${index}`}>{item.productName} · Quantity {item.quantity}</p>)}</> : <p>This order tracking record is unavailable.</p>}</div>}</> : <Empty title="No orders yet" detail="Your confirmed VAMNUX order history will appear here." action={<button className="account-hub-link" onClick={() => setTab("catalogs")}>Browse catalog</button>} />}</section>;
    if (tab === "wallet") return <section className="account-hub-panel"><header><div><span>VAMNUX WALLET</span><h2>{money(data.wallet.availableBalance, data.wallet.currency)}</h2><p>Your balance changes only through real, authorised server-side wallet records.</p></div><WalletCards size={25} /></header><form className="account-hub-form" onSubmit={submitTopUp}><h3>Request wallet funding</h3><p>Provider checkout remains inactive. A submitted request is reviewed before any balance credit.</p><div className="account-hub-fields"><label>Amount<input inputMode="decimal" value={topUpAmount} onChange={(event) => setTopUpAmount(event.target.value)} placeholder="0.00" required /></label><label>Currency<input value={data.wallet.currency} readOnly /></label></div><label>Reference note <small>Optional</small><input value={topUpNote} onChange={(event) => setTopUpNote(event.target.value)} maxLength={500} placeholder="Add a note after you receive payment instructions." /></label><button className="account-hub-primary" disabled={fundWallet.isPending}>{fundWallet.isPending ? "Submitting…" : "Submit funding request"} <ArrowRight size={15} /></button></form><section className="account-hub-subsection"><h3>Funding requests</h3>{data.fundingRequests.length ? <div className="account-hub-list">{data.fundingRequests.map((request) => <div key={request.fundingCode}><span><b>{request.fundingCode}</b><small>{new Date(request.createdAt).toLocaleString()}</small></span><em>{label(request.status)}</em><strong>{money(request.amount, request.currency)}</strong></div>)}</div> : <Empty title="No funding requests" detail="Any request you submit will appear with its actual review state." />}</section></section>;
    if (tab === "transactions") return <section className="account-hub-panel"><header><div><span>TRANSACTIONS</span><h2>Wallet activity</h2><p>Payments are not collected here; this shows only immutable VAMNUX wallet entries.</p></div><ReceiptText size={24} /></header>{data.walletEntries.length ? <div className="account-hub-list">{data.walletEntries.map((entry) => <div key={entry.id}><span><b>{label(entry.entryType)}</b><small>{entry.reference} · {new Date(entry.createdAt).toLocaleString()}</small></span><em>{entry.status}</em><strong className={entry.direction === "credit" ? "credit" : "debit"}>{entry.direction === "credit" ? "+" : "−"}{money(entry.amount, entry.currency)}</strong></div>)}</div> : <Empty title="No wallet transactions" detail="Verified credits, purchases, refunds, or adjustments will appear here when they are actually recorded." />}</section>;
    if (tab === "favorites") return <section className="account-hub-panel"><header><div><span>FAVORITES</span><h2>Saved products</h2><p>Keep real VAMNUX products here to find them later.</p></div><Heart size={24} /></header>{data.savedProducts.length ? <div className="account-hub-saved-grid">{data.savedProducts.map((product) => <article key={product.savedId}><span>{product.category}</span><h3>{product.name}</h3><p>{product.regionLabel || "Regional supplier rules"} · {label(product.deliveryType)}</p><div><strong>{money(product.customerPrice, "USD")}</strong><button onClick={() => saveProduct.mutate({ productId: product.id })} aria-label={`Remove ${product.name} from favorites`}><Heart size={16} fill="currentColor" /></button></div><Link href={`/products/${product.slug}`}>View product <ArrowRight size={14} /></Link></article>)}</div> : <Empty title="Your favorites are empty" detail="Save an active product from a product page to see it here." action={<button className="account-hub-link" onClick={() => setTab("catalogs")}>Browse catalog</button>} />}</section>;
    if (tab === "buyAgain") return <section className="account-hub-panel"><header><div><span>BUY AGAIN</span><h2>Repeat a past need</h2><p>Choose a recent product journey, then review the current catalog pricing and requirements before any draft order.</p></div><RefreshCw size={24} /></header>{orders.length ? <div className="account-hub-list">{orders.slice(0, 6).map((order) => <Link key={order.orderCode} href="/"><span><b>{order.orderCode}</b><small>Open the current VAMNUX catalog to choose a fresh product selection.</small></span><em>{label(order.status)}</em><ArrowRight size={16} /></Link>)}</div> : <Empty title="Nothing to buy again yet" detail="Your past VAMNUX order journeys will appear here once recorded." action={<Link className="account-hub-link" href="/">Browse catalog</Link>} />}</section>;
    if (tab === "rewards") return <section className="account-hub-panel"><header><div><span>REWARDS & LOYALTY</span><h2>VAMNUX rewards</h2></div><Star size={24} /></header><Inactive title="Rewards are not active" detail="VAMNUX has no active customer-points or reward-redemption programme yet, so no points or earnings are being represented." /></section>;
    if (tab === "referrals") return <section className="account-hub-panel"><header><div><span>REFERRALS</span><h2>Invite & earn</h2></div><Gift size={24} /></header><Inactive title="Referral earnings are not active" detail="VAMNUX does not currently issue referral links or credit referral earnings. This workspace will display only real programme records if the owner activates the programme." /></section>;
    if (tab === "subscriptions") return <section className="account-hub-panel"><header><div><span>SUBSCRIPTIONS</span><h2>Active passes</h2></div><Tv size={24} /></header><Inactive title="No active subscriptions" detail="VAMNUX does not currently provision, renew, or manage customer subscriptions or passes. Active items will appear only when a supported product and fulfilment workflow are enabled." /></section>;
    if (tab === "notifications") return <section className="account-hub-panel"><header><div><span>NOTIFICATIONS</span><h2>Account alerts</h2><p>Private order, wallet, support, and security updates for your account.</p></div><Bell size={24} /></header>{data.notifications.length ? <div className="account-hub-list">{data.notifications.map((notification) => <div key={notification.id} className={notification.readAt ? "" : "unread"}><span><b>{notification.title}</b><small>{notification.body} · {new Date(notification.createdAt).toLocaleString()}</small></span>{!notification.readAt && <button onClick={() => markRead.mutate({ notificationId: notification.id })}>Mark read</button>}</div>)}</div> : <Empty title="No notifications yet" detail="Authorised account notifications will appear here." />}</section>;
    if (tab === "support") return <section className="account-hub-panel"><header><div><span>SUPPORT</span><h2>How can we help?</h2><p>Tickets remain private to your signed-in VAMNUX account.</p></div><CircleHelp size={24} /></header><form className="account-hub-form" onSubmit={submitTicket}><div className="account-hub-fields"><label>Category<select name="category" defaultValue="order"><option value="order">Order</option><option value="wallet">Wallet</option><option value="account">Account</option><option value="game_top_up">Game top-up</option><option value="gift_card">Gift card</option><option value="subscription">Subscription</option><option value="software">Software</option><option value="refund">Refund</option><option value="other">Other</option></select></label><label>Related order <small>Optional</small><select name="orderCode"><option value="">No related order</option>{orders.map((order) => <option key={order.orderCode} value={order.orderCode}>{order.orderCode}</option>)}</select></label></div><label>Subject<input name="subject" maxLength={180} required /></label><label>Message<textarea name="message" maxLength={5000} required /></label><button className="account-hub-primary" disabled={createTicket.isPending}>{createTicket.isPending ? "Submitting…" : "Submit support ticket"} <ArrowRight size={15} /></button></form><section className="account-hub-subsection"><h3>Ticket history</h3>{data.tickets.length ? <div className="account-hub-list">{data.tickets.map((ticket) => <div key={ticket.ticketCode}><span><b>{ticket.ticketCode} · {ticket.subject}</b><small>{label(ticket.category)} · Updated {new Date(ticket.updatedAt).toLocaleString()}</small></span><em>{label(ticket.status)}</em></div>)}</div> : <Empty title="No support tickets" detail="Tickets submitted from this secure account appear here." />}</section></section>;
    if (tab === "profile") return <section className="account-hub-panel"><header><div><span>PROFILE</span><h2>Your VAMNUX details</h2><p>Update your marketplace profile without changing the secured sign-in identity.</p></div><UserRound size={24} /></header><form className="account-hub-form" onSubmit={submitProfile}><div className="account-hub-fields"><label>First name<input value={profile.firstName} onChange={(event) => setProfile({ ...profile, firstName: event.target.value })} maxLength={80} required /></label><label>Last name<input value={profile.lastName} onChange={(event) => setProfile({ ...profile, lastName: event.target.value })} maxLength={80} required /></label><label>Username <small>Optional</small><input value={profile.username} onChange={(event) => setProfile({ ...profile, username: event.target.value })} maxLength={30} /></label><label>Phone <small>Optional</small><input value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} maxLength={32} /></label><label>Country code<input value={profile.countryCode} onChange={(event) => setProfile({ ...profile, countryCode: event.target.value.toUpperCase() })} maxLength={2} placeholder="NG" /></label><label>Sign-in email<input value={user.email || "Not available"} readOnly /></label></div><button className="account-hub-primary" disabled={saveProfile.isPending}>{saveProfile.isPending ? "Saving…" : "Save profile"} <ArrowRight size={15} /></button></form></section>;
    if (tab === "security") return <section className="account-hub-panel"><header><div><span>SECURITY</span><h2>Account protection</h2><p>Only actual security activity and configured account controls are presented here.</p></div><LockKeyhole size={24} /></header><div className="account-hub-security-grid"><article><MailCheck size={18} /><h3>Email status</h3><p>{label(data.profile?.accountStatus || "active")}</p><small>Verification emails stay unavailable until VAMNUX configures a verified sender.</small></article><article><KeyRound size={18} /><h3>Password & MFA</h3><p>{isNative ? "Password account active" : "Manus OAuth account active"}</p><small>MFA is not configured. Password recovery is available only when transactional email is configured.</small></article><article><ShieldCheck size={18} /><h3>Sessions</h3><p>This signed-in session is active.</p>{isNative ? <button onClick={() => logoutAll.mutate()} disabled={logoutAll.isPending}>Sign out all password sessions</button> : <small>Manus OAuth session controls remain managed by the identity provider.</small>}</article></div><section className="account-hub-subsection"><h3>Login & account activity</h3>{data.securityEvents.length ? <div className="account-hub-list">{data.securityEvents.map((event) => <div key={event.id}><span><b>{event.summary}</b><small>{label(event.eventType)}</small></span><em>{new Date(event.createdAt).toLocaleString()}</em></div>)}</div> : <Empty title="No security events yet" detail="Successful sign-ins and authorised account-security events will appear here." />}</section></section>;
    if (tab === "settings") return <section className="account-hub-panel"><header><div><span>SETTINGS</span><h2>Preferences</h2><p>Set your display currency and notification choices.</p></div><Settings2 size={24} /></header><form className="account-hub-form" onSubmit={submitSettings}><div className="account-hub-fields"><label>Display currency<select value={currency} onChange={(event) => setCurrency(event.target.value)}><option value="USD">USD — US Dollar</option><option value="EUR">EUR — Euro</option><option value="GBP">GBP — British Pound</option><option value="NGN">NGN — Nigerian Naira</option></select></label><label>Country code <small>Optional</small><input value={profile.countryCode} onChange={(event) => setProfile({ ...profile, countryCode: event.target.value.toUpperCase() })} maxLength={2} /></label></div><button className="account-hub-primary" disabled={savePreferences.isPending}>{savePreferences.isPending ? "Saving…" : "Save preferences"} <ArrowRight size={15} /></button></form><form className="account-hub-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); saveNotifications.mutate({ orderUpdates: form.get("orders") === "on", paymentUpdates: form.get("payments") === "on", walletUpdates: form.get("wallet") === "on", marketingUpdates: form.get("marketing") === "on", productAnnouncements: form.get("products") === "on" }); }}><h3>Notifications</h3><div className="account-hub-checks"><label><input type="checkbox" name="orders" defaultChecked={data.notificationPreferences?.orderUpdates ?? true} /> Order updates</label><label><input type="checkbox" name="payments" defaultChecked={data.notificationPreferences?.paymentUpdates ?? true} /> Payment updates</label><label><input type="checkbox" name="wallet" defaultChecked={data.notificationPreferences?.walletUpdates ?? true} /> Wallet updates</label><label><input type="checkbox" name="marketing" defaultChecked={data.notificationPreferences?.marketingUpdates ?? false} /> Marketing updates</label><label><input type="checkbox" name="products" defaultChecked={data.notificationPreferences?.productAnnouncements ?? false} /> Product announcements</label></div><button className="account-hub-secondary" disabled={saveNotifications.isPending}>{saveNotifications.isPending ? "Saving…" : "Save notification choices"}</button></form></section>;
    if (tab === "privacy") return <section className="account-hub-panel"><header><div><span>PRIVACY</span><h2>Your data choices</h2><p>Submit a protected request for your VAMNUX account data or a deletion review.</p></div><ShieldCheck size={24} /></header><div className="account-hub-privacy-actions"><button onClick={() => createPrivacyRequest.mutate({ requestType: "data_access" })}>Request account information</button><button onClick={() => createPrivacyRequest.mutate({ requestType: "data_correction" })}>Request a correction</button><button onClick={() => createPrivacyRequest.mutate({ requestType: "account_deletion" })}>Request account deletion review</button></div><section className="account-hub-subsection"><h3>Request history</h3>{data.privacyRequests.length ? <div className="account-hub-list">{data.privacyRequests.map((request) => <div key={request.requestCode}><span><b>{request.requestCode}</b><small>{label(request.requestType)} · {new Date(request.createdAt).toLocaleString()}</small></span><em>{label(request.status)}</em></div>)}</div> : <Empty title="No privacy requests" detail="Requests submitted from this account appear here with their real status." />}</section><section className="account-hub-subsection"><h3>Policy drafts</h3><div className="account-hub-policy-links">{data.policyPages.map((page) => <Link key={page.slug} href={`/policies/${page.slug}`}>{page.title}<small>{page.status} · {page.version}</small><ArrowRight size={14} /></Link>)}</div></section></section>;
    return null;
  };

  return <main className="account-hub"><header className="account-hub-top"><Link href="/" className="account-hub-brand"><span>V</span>VAM<em>NUX</em></Link><div><button onClick={() => setTab("wallet")}><WalletCards size={15} />{money(data.wallet.availableBalance, data.wallet.currency)}</button><button onClick={() => setTab("profile")}><UserRound size={15} />{displayName}</button><button onClick={logout} aria-label="Sign out"><LogOut size={16} /></button></div></header><div className="account-hub-shell"><aside className="account-hub-sidebar"><div className="account-hub-person"><span>{displayName.charAt(0).toUpperCase()}</span><div><b>{displayName}</b><small>{user.email || "VAMNUX account"}</small></div></div><nav>{navigationGroups.map((group) => <section key={group.label}><p>{group.label}</p>{group.items.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={tab === item.id ? "active" : ""}><Icon size={16} />{item.label}</button>; })}</section>)}<Link href="/" className="account-hub-market-link"><FolderOpen size={16} />Marketplace <ArrowRight size={14} /></Link></nav></aside><section className="account-hub-content">{render()}</section></div><nav className="account-hub-mobile-nav">{["overview", "catalogs", "wallet", "orders", "profile"].map((id) => { const item = navigationGroups.flatMap((group) => group.items).find((entry) => entry.id === id); if (!item) return null; const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={tab === item.id ? "active" : ""}><Icon size={17} /><span>{item.label}</span></button>; })}</nav></main>;
}
