export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "VAMNUX <no-reply@send.vamnux.com>",
  adminEmail: process.env.VAMNUX_ADMIN_EMAIL ?? "",
  nativeAuthPublicUrl: process.env.VAMNUX_PUBLIC_APP_URL ?? "https://vamnux.com",
  nativeAuthEnabled: process.env.VAMNUX_NATIVE_AUTH_ENABLED === "true",
  localUploadDir: process.env.VAMNUX_UPLOAD_DIR ?? "",
  productTrackingCronSecret: process.env.PRODUCT_TRACKING_CRON_SECRET ?? "",
  paystackTestSecretKey: process.env.PAYSTACK_TEST_SECRET_KEY ?? "",
  paystackTestCallbackUrl: process.env.PAYSTACK_TEST_CALLBACK_URL ?? "",
};
