import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { displayOwnerName } from "@shared/adminAuthentication";
import { BellRing, CheckCircle2, Copy, KeyRound, LockKeyhole, LogOut, MailCheck, MonitorSmartphone, Phone, QrCode, Save, ShieldAlert, ShieldCheck, Smartphone, UserRoundCog } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import "./adminSettingsWorkspace.css";

type SettingsSection = "profile" | "protection" | "notifications" | "sessions" | "recovery";
type ProfileDraft = { firstName: string; lastName: string; username: string; phone: string; countryCode: string };
type Enrollment = { qrDataUrl: string; manualKey: string; issuer: string; accountLabel: string };
const emptyProfile: ProfileDraft = { firstName: "", lastName: "", username: "", phone: "", countryCode: "" };

export function AdminAuthenticationSettings({ onSignOut }: { onSignOut: () => void }) {
  const utils = trpc.useUtils();
  const [section, setSection] = useState<SettingsSection>("profile");
  const [profile, setProfile] = useState<ProfileDraft>(emptyProfile);
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null);
  const [authenticatorCode, setAuthenticatorCode] = useState("");
  const [recoveryCode, setRecoveryCode] = useState("");
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const dashboard = trpc.marketplace.customerDashboard.useQuery();
  const currentUser = trpc.auth.me.useQuery();
  const mfa = trpc.admin.mfaStatus.useQuery();
  const preferences = dashboard.data?.notificationPreferences;
  const saveProfile = trpc.marketplace.updateCustomerProfile.useMutation({ onSuccess: async () => { toast.success("Owner profile details saved."); await utils.marketplace.customerDashboard.invalidate(); }, onError: (error) => toast.error(error.message || "Could not save owner profile details.") });
  const saveAlerts = trpc.marketplace.updateNotificationPreferences.useMutation({ onSuccess: async () => { toast.success("Security-alert preference saved."); await utils.marketplace.customerDashboard.invalidate(); }, onError: (error) => toast.error(error.message || "Could not save the security-alert preference.") });
  const beginMfa = trpc.admin.startMfaEnrollment.useMutation({ onSuccess: (data) => { setEnrollment(data); setAuthenticatorCode(""); toast.message("Scan the QR code, then confirm the next authenticator code."); }, onError: (error) => toast.error(error.message || "Could not start authenticator setup.") });
  const confirmMfa = trpc.admin.confirmMfaEnrollment.useMutation({ onSuccess: async (data) => { setRecoveryCodes(data.recoveryCodes); setEnrollment(null); setAuthenticatorCode(""); await utils.admin.mfaStatus.invalidate(); toast.success("Authenticator MFA is active. Save the recovery codes shown once."); }, onError: (error) => toast.error(error.message || "Authenticator code could not be confirmed.") });
  const regenerateCodes = trpc.admin.regenerateMfaRecoveryCodes.useMutation({ onSuccess: async (data) => { setRecoveryCodes(data.recoveryCodes); setRecoveryCode(""); await utils.admin.mfaStatus.invalidate(); toast.success("Previous recovery codes are now invalid. Save the new codes shown once."); }, onError: (error) => toast.error(error.message || "Enter a current authenticator code to replace recovery codes.") });
  useEffect(() => { const saved = dashboard.data?.profile; if (saved) setProfile({ firstName: saved.firstName || "", lastName: saved.lastName || "", username: saved.username || "", phone: saved.phone || "", countryCode: saved.countryCode || "" }); }, [dashboard.data?.profile]);
  const ownerName = displayOwnerName(dashboard.data?.profile, currentUser.data?.name);
  const saveOwnerProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!window.confirm("Save these owner profile details? Your VAMNUX sign-in email is not changed.")) return; saveProfile.mutate({ firstName: profile.firstName.trim() || null, lastName: profile.lastName.trim() || null, username: profile.username.trim() || null, phone: profile.phone.trim() || null, countryCode: profile.countryCode.trim().toUpperCase() || null, registrationSource: null }); };
  const setSecurityAlerts = (next: boolean) => { if (!preferences) return; saveAlerts.mutate({ orderUpdates: preferences.orderUpdates, paymentUpdates: preferences.paymentUpdates, walletUpdates: preferences.walletUpdates, marketingUpdates: preferences.marketingUpdates, productAnnouncements: preferences.productAnnouncements, securityAlerts: next }); };
  const copy = async (value: string, label: string) => { try { await navigator.clipboard.writeText(value); toast.success(`${label} copied. Keep it private.`); } catch { toast.error("Copy is unavailable in this browser. Select the value manually."); } };
  const nav = (id: SettingsSection, title: string, Icon: typeof UserRoundCog) => <button type="button" className={section === id ? "active" : ""} onClick={() => setSection(id)}><Icon size={16} />{title}</button>;

  return <section className="admin-panel admin-settings-workspace"><header><div><span>SETTINGS</span><h2>Owner account & sign-in security</h2><p>Manage VAMNUX owner profile details, current-session protection, authenticator MFA, recovery, and in-app security-alert preferences. Passwords remain securely hashed on the VAMNUX server.</p></div><LockKeyhole size={21} /></header>
    <section className="admin-metric-grid"><article><span>OWNER ACCESS</span><strong>Protected</strong><small>Role and MFA checks</small></article><article><span>IDENTITY EMAIL</span><strong className="text-[20px]">{currentUser.data?.email ? "VAMNUX account" : "Unavailable"}</strong><small>{currentUser.data?.email || "No email returned"}</small></article><article><span>SECURITY ALERTS</span><strong>{preferences?.securityAlerts ? "On" : "Off"}</strong><small>Stored in-app preference</small></article><article><span>AUTHENTICATOR</span><strong>{mfa.data?.enrolled ? "Active" : "Not enrolled"}</strong><small>{mfa.data?.enrolled ? `${mfa.data.recoveryCodesRemaining} recovery codes left` : "Set up now"}</small></article></section>
    <div className="admin-settings-layout"><aside><p>ACCOUNT SETTINGS</p>{nav("profile", "General profile", UserRoundCog)}{nav("protection", "Sign-in protection", LockKeyhole)}{nav("notifications", "Security alerts", BellRing)}{nav("sessions", "Current session", MonitorSmartphone)}{nav("recovery", "Recovery readiness", KeyRound)}<div className="admin-settings-side-note"><ShieldCheck size={16} />Profile edits do not change your VAMNUX sign-in email or weaken owner authorization.</div></aside>
      <div className="admin-settings-content">
        {section === "profile" && <form className="admin-settings-profile-form" onSubmit={saveOwnerProfile}><div><p className="admin-form-kicker">GENERAL</p><h3>Owner profile</h3><p>Save the owner name, username, country code, and recovery contact number. Phone verification is not claimed until a real SMS or voice service is connected.</p></div><div className="admin-settings-field-grid"><label>First name<input value={profile.firstName} maxLength={80} onChange={(event) => setProfile({ ...profile, firstName: event.target.value })} /></label><label>Last name<input value={profile.lastName} maxLength={80} onChange={(event) => setProfile({ ...profile, lastName: event.target.value })} /></label><label>Username<input value={profile.username} maxLength={30} placeholder="vamnux-owner" onChange={(event) => setProfile({ ...profile, username: event.target.value })} /></label><label>Country code<input value={profile.countryCode} maxLength={2} placeholder="NG" onChange={(event) => setProfile({ ...profile, countryCode: event.target.value.toUpperCase() })} /></label></div><label>Recovery contact phone <small>not verified</small><input value={profile.phone} maxLength={32} inputMode="tel" placeholder="+234…" onChange={(event) => setProfile({ ...profile, phone: event.target.value })} /></label><div className="admin-policy-note"><MailCheck size={15} /><span><strong>Current sign-in email:</strong> {currentUser.data?.email || "Unavailable"}. It is owned by the active identity provider and cannot be edited here.</span></div><button type="submit" className="admin-primary-action" disabled={saveProfile.isPending}>{saveProfile.isPending ? "Saving…" : "Save owner details"}<Save size={14} /></button></form>}
        {section === "protection" && <div className="admin-settings-section"><div><p className="admin-form-kicker">SIGN-IN PROTECTION</p><h3>Authenticator MFA</h3><p>When confirmed, a fresh authenticator or recovery-code challenge is required after the next secure Admin sign-in.</p></div><article className="admin-settings-security-card"><Smartphone size={20} /><div><strong>Two-factor authentication</strong><p>{mfa.data?.enrolled ? "Authenticator MFA is active for future Admin sign-ins." : "Use a compatible authenticator app to add a second security factor."}</p></div><span className={`admin-status ${mfa.data?.enrolled ? "good" : "muted"}`}>{mfa.data?.enrolled ? "Active" : "Not enrolled"}</span></article>{!mfa.data?.enrolled && !enrollment && <button type="button" className="admin-primary-action" onClick={() => beginMfa.mutate()} disabled={beginMfa.isPending}>{beginMfa.isPending ? "Preparing…" : "Set up authenticator"}</button>}{enrollment && <section className="admin-settings-enrollment"><p className="admin-form-kicker">AUTHENTICATOR ENROLLMENT</p><h4>Scan, then confirm a new code</h4><div><img src={enrollment.qrDataUrl} alt="Authenticator setup QR code" /><div><p>Scan the code in an authenticator app. The secret below is visible only during this enrollment step.</p><code>{enrollment.manualKey}</code><button type="button" className="admin-secondary-action" onClick={() => copy(enrollment.manualKey, "Manual key")}><Copy size={13} />Copy key</button><label>Enter the next six-digit code<input value={authenticatorCode} inputMode="numeric" placeholder="123456" onChange={(event) => setAuthenticatorCode(event.target.value.replace(/\D/g, "").slice(0, 6))} /></label><button type="button" className="admin-primary-action" disabled={authenticatorCode.length !== 6 || confirmMfa.isPending} onClick={() => confirmMfa.mutate({ code: authenticatorCode })}>{confirmMfa.isPending ? "Confirming…" : "Confirm and activate MFA"}</button></div></div></section>}</div>}
        {section === "notifications" && <div className="admin-settings-section"><div><p className="admin-form-kicker">SECURITY ALERTS</p><h3>Alert preference & password reset</h3><p>Security alerts are stored in VAMNUX. Password reset links are delivered through the verified VAMNUX email service.</p></div><article className="admin-settings-security-card"><BellRing size={20} /><div><strong>Keep in-app security alerts enabled</strong><p>Separate from marketing preferences. Email, SMS, and WhatsApp delivery are not configured.</p></div><button type="button" role="switch" aria-checked={preferences?.securityAlerts ?? true} disabled={!preferences || saveAlerts.isPending} className={preferences?.securityAlerts ?? true ? "admin-primary-action" : "admin-secondary-action"} onClick={() => setSecurityAlerts(!(preferences?.securityAlerts ?? true))}>{saveAlerts.isPending ? "Saving…" : preferences?.securityAlerts ? "Alerts on" : "Alerts off"}</button></article><article className="admin-settings-password-reset"><div><KeyRound size={19} /><p className="admin-form-kicker">PASSWORD RESET</p><h4>Request a secure reset link</h4><p>Open the VAMNUX recovery page. A one-time link will be sent only if the account email is verified.</p></div><a href="/login?mode=recovery" className="admin-primary-action">Open account recovery <LockKeyhole size={14} /></a></article></div>}
        {section === "sessions" && <div className="admin-settings-section"><div><p className="admin-form-kicker">CURRENT SESSION</p><h3>Current secure session</h3><p>VAMNUX can clear this browser session. A password reset also safely revokes existing VAMNUX account sessions.</p></div><article className="admin-settings-security-card"><MonitorSmartphone size={20} /><div><strong>Current browser session</strong><p>Signed in as {ownerName}. Last sign-in: {currentUser.data?.lastSignedIn ? new Date(currentUser.data.lastSignedIn).toLocaleString() : "Unavailable"}.</p></div><button type="button" className="admin-danger-action" onClick={onSignOut}><LogOut size={14} />Sign out</button></article></div>}
        {section === "recovery" && <div className="admin-settings-section"><div><p className="admin-form-kicker">RECOVERY & ACTIVITY</p><h3>Recovery codes and safe activity</h3><p>Recovery codes are single-use and only shown when generated. Device fingerprints, IP addresses, tokens, and secrets are excluded.</p></div>{mfa.data?.enrolled ? <section className="admin-settings-recovery"><strong>{mfa.data.recoveryCodesRemaining} recovery codes remaining</strong><p>Replacing codes immediately invalidates every older code.</p><label>Current authenticator code<input value={recoveryCode} inputMode="numeric" placeholder="123456" onChange={(event) => setRecoveryCode(event.target.value.replace(/\D/g, "").slice(0, 6))} /></label><button type="button" className="admin-secondary-action" disabled={recoveryCode.length !== 6 || regenerateCodes.isPending} onClick={() => regenerateCodes.mutate({ code: recoveryCode })}>{regenerateCodes.isPending ? "Replacing…" : "Replace recovery codes"}</button></section> : <article className="admin-settings-security-card"><QrCode size={20} /><div><strong>Authenticator setup is required first</strong><p>Activate an authenticator in Sign-in protection before generating recovery codes.</p></div></article>}{recoveryCodes.length > 0 && <section className="admin-settings-recovery"><strong>Save these recovery codes now</strong><p>They will not be shown again. Store them offline and do not send them by chat or email.</p><div className="admin-settings-code-grid">{recoveryCodes.map((code) => <code key={code}>{code}</code>)}</div><button type="button" className="admin-secondary-action" onClick={() => copy(recoveryCodes.join("\n"), "Recovery codes")}><Copy size={13} />Copy codes once</button></section>}<section className="admin-settings-activity"><strong>Recent account security activity</strong>{dashboard.isLoading ? <p>Loading security activity…</p> : dashboard.data?.securityEvents.length ? dashboard.data.securityEvents.map((event) => <article key={event.id}><strong>{event.summary}</strong><time>{new Date(event.createdAt).toLocaleString()}</time><span>{event.eventType.replaceAll("_", " ")}</span></article>) : <p>No stored security activity is available yet.</p>}</section></div>}
      </div>
    </div>
  </section>;
}
