import { trpc } from "@/lib/trpc";
import { SUPPLIER_API_ACCESS_METADATA } from "@shared/supplierApiAccess";
import { Copy, ExternalLink, Eye, EyeOff, KeyRound, LockKeyhole, Mail, MessageCircleMore, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import "./adminApiAccessControl.css";

export function AdminApiAccessControl() {
  const { data, isLoading } = trpc.admin.apiAccessControlStatus.useQuery();
  const [revealed, setRevealed] = useState<Record<string, boolean>>({});
  const copyReference = async (reference: string) => {
    try { await navigator.clipboard.writeText(reference); toast.success("Secure configuration reference copied. Credential values remain server-only."); }
    catch { toast.error("Copy is unavailable in this browser. Select the configuration reference manually."); }
  };
  const statusFor = (supplierKey: string, reference: string) => data?.find((supplier) => supplier.key === supplierKey)?.credentials.find((credential) => credential.reference === reference);
  return <section className="admin-panel admin-api-access-control"><header><div><span>API ACCESS CONTROL</span><h2>Supplier connection security</h2><p>Review verified supplier partner information and server-only credential readiness. Live API values are never shown, copied, logged, or sent to this browser.</p></div><KeyRound size={21} /></header>
    <section className="admin-api-access-note"><ShieldCheck size={18} /><div><strong>Credentials remain server-only</strong><p>Show controls reveal only protected status, never a key, token, secret, or webhook signature. Copy controls copy the secure configuration reference, not the credential value.</p></div></section>
    <div className="admin-api-access-list">{SUPPLIER_API_ACCESS_METADATA.map((supplier) => <article key={supplier.key}><div className="admin-api-access-heading"><div><span>{supplier.name}</span><p>Configured VAMNUX supplier integration</p></div><i>Owner-only</i></div><div className="admin-api-access-links"><a href={supplier.websiteUrl} target="_blank" rel="noreferrer">Supplier website <ExternalLink size={13} /></a><a href={supplier.documentationUrl} target="_blank" rel="noreferrer">API documentation <ExternalLink size={13} /></a>{supplier.partnerUrl && <a href={supplier.partnerUrl} target="_blank" rel="noreferrer">Partner portal <ExternalLink size={13} /></a>}</div><div className="admin-api-access-columns"><section><p className="admin-form-kicker">PUBLIC CONTACT CHANNELS</p>{supplier.contacts.length ? <div className="admin-api-contact-list">{supplier.contacts.map((contact) => <a key={`${contact.label}-${contact.value}`} href={contact.href} target={contact.href?.startsWith("http") ? "_blank" : undefined} rel={contact.href?.startsWith("http") ? "noreferrer" : undefined}>{contact.label === "Support email" ? <Mail size={14} /> : <MessageCircleMore size={14} />}<span><small>{contact.label}</small><strong>{contact.value}</strong></span></a>)}</div> : <p className="admin-api-empty">No verified public support channel is stored here. Use the supplier website or partner portal.</p>}</section><section><p className="admin-form-kicker">SERVER-ONLY CREDENTIAL STATUS</p><div className="admin-api-credential-list">{supplier.credentials.map((credential) => { const status = statusFor(supplier.key, credential.reference); const id = `${supplier.key}-${credential.reference}`; const open = revealed[id]; return <div key={credential.reference}><div><strong>{credential.label}</strong><small>{isLoading ? "Checking protected configuration…" : status?.configured ? "Configured server-side" : "Not configured"}</small></div><code aria-label={`Secure configuration reference for ${credential.label}`}>{open ? credential.reference : "••••••••••••••••"}</code><button type="button" aria-label={open ? `Hide ${credential.label} configuration reference` : `Show ${credential.label} configuration reference`} onClick={() => setRevealed((current) => ({ ...current, [id]: !current[id] }))}>{open ? <EyeOff size={15} /> : <Eye size={15} />}</button><button type="button" aria-label={`Copy ${credential.label} configuration reference`} onClick={() => copyReference(credential.reference)}><Copy size={15} /></button></div>; })}</div></section></div></article>)}</div>
    <section className="admin-api-access-note muted"><LockKeyhole size={18} /><div><strong>Rotate credentials securely</strong><p>Use your secure configuration settings to change a supplier credential. This workspace intentionally provides no secret-reveal, secret-copy, or browser credential entry action.</p></div></section>
  </section>;
}
