import { AlertTriangle, BarChart3, Calculator, Landmark, Loader2, ShieldCheck, SlidersHorizontal, TrendingDown, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { FULFILLMENT_ORDER_STATUSES, type FulfillmentOrderStatus } from "@shared/supplierFulfillment";
import "./adminFinancialControls.css";

const categories = ["top_up", "gift_card", "game_key", "subscription", "ai_tool", "software", "steam", "steam_top_up", "telegram_stars"] as const;
const currencies = ["USD", "NGN", "EUR", "GBP"] as const;
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const money = (value: number | null | undefined, currency = "USD") => new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 2 }).format(value ?? 0);
const asAmount = (value: string) => Number.isFinite(Number(value)) ? Math.max(0, Number(value)) : 0;
type ProfitRow = { key: string; label: string; records: number; grossRevenue: number; supplierCost: number; grossProfit: number; paymentFees: number; refunds: number; netRevenue: number; netProfit: number; profitMarginPercent: number };
type FinancialRecord = { id: number; orderReference: string; sourceType: string; productName: string; category: string | null; supplierKey: string | null; customerSellingPrice: number; customerCurrency: string; supplierCostInCustomerCurrency: number | null; paymentProcessingFee: number; otherApplicableFees: number; netProfit: number; profitMarginPercent: number; orderStatus: string; createdAt: Date };
type FinancialAlert = { type: string; snapshotId: number; orderReference: string; productName: string; supplierKey: string | null; category: string | null; currency: string; sellingPrice: number; supplierCost: number | null; profitMarginPercent: number; createdAt: Date };

export function AdminFinancialControls() {
  const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState(""); const [productId, setProductId] = useState(""); const [category, setCategory] = useState(""); const [supplierKey, setSupplierKey] = useState(""); const [currency, setCurrency] = useState(""); const [orderStatus, setOrderStatus] = useState("");
  const [preview, setPreview] = useState({ selling: "1.00", supplier: "0.75", rate: "1", converted: "0.75", processingFee: "0", otherFee: "0", refund: "0", feeConfigured: false });
  const [previewRequested, setPreviewRequested] = useState(false);
  const filters = useMemo(() => ({ start: fromDate ? new Date(`${fromDate}T00:00:00`) : undefined, end: toDate ? new Date(`${toDate}T23:59:59`) : undefined, productId: productId ? Number(productId) : undefined, category: category ? category as typeof categories[number] : undefined, supplierKey: supplierKey.trim() || undefined, currency: currency ? currency as typeof currencies[number] : undefined, orderStatus: orderStatus ? orderStatus as FulfillmentOrderStatus : undefined }), [fromDate, toDate, productId, category, supplierKey, currency, orderStatus]);
  const dashboardQuery = trpc.admin.getFinancialControlsDashboard.useQuery(filters, { refetchOnWindowFocus: true });
  const previewInput = useMemo(() => ({ customerSellingPrice: asAmount(preview.selling), supplierCost: preview.supplier.trim() ? asAmount(preview.supplier) : null, exchangeRate: preview.rate.trim() ? asAmount(preview.rate) || null : null, supplierCostInCustomerCurrency: preview.converted.trim() ? asAmount(preview.converted) : null, paymentProcessingFee: asAmount(preview.processingFee), otherApplicableFees: asAmount(preview.otherFee), refundAmount: asAmount(preview.refund), paymentFeeConfigured: preview.feeConfigured }), [preview]);
  const previewQuery = trpc.admin.previewFinancialControls.useQuery(previewInput, { enabled: previewRequested, refetchOnWindowFocus: false });
  const dashboard = dashboardQuery.data;
  const summary = dashboard?.summary;
  const records = (dashboard?.records ?? []) as FinancialRecord[];
  const alerts = (dashboard?.alerts ?? []) as FinancialAlert[];
  const rollups = dashboard?.profitability;
  const clearFilters = () => { setFromDate(""); setToDate(""); setProductId(""); setCategory(""); setSupplierKey(""); setCurrency(""); setOrderStatus(""); };
  const updatePreview = (key: keyof typeof preview, value: string | boolean) => { setPreview((current) => ({ ...current, [key]: value })); setPreviewRequested(false); };
  return <section className="financial-controls" aria-label="Financial and Profit Controls">
    <header className="financial-header"><div><span>VAMNUX FINANCIAL CONTROLS</span><h2>Profitability from immutable history.</h2><p>This Admin-only workspace reads server-side financial snapshots and append-only financial events. It never reprices a product, updates a supplier cost, or moves money.</p></div><Landmark size={25} /></header>
    <section className="financial-boundary"><ShieldCheck size={18} /><div><strong>ANALYSIS ONLY — NO COMMERCIAL ACTION</strong><p>Payment providers, live charges, wallet changes, refunds, supplier changes, and price applications remain outside this workspace. Every future snapshot preserves its original commercial values.</p></div></section>
    <section className="financial-filters"><div className="financial-heading"><div><span>FILTER FINANCIAL HISTORY</span><h3>Inspect the same immutable records from different angles</h3></div><SlidersHorizontal size={20} /></div><div className="financial-filter-grid"><label>From date<input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label>To date<input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label><label>Product ID<input inputMode="numeric" value={productId} onChange={(event) => setProductId(event.target.value.replace(/\D/g, ""))} placeholder="Exact product ID" /></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All categories</option>{categories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>Supplier<input value={supplierKey} onChange={(event) => setSupplierKey(event.target.value)} placeholder="Supplier ID" /></label><label>Currency<select value={currency} onChange={(event) => setCurrency(event.target.value)}><option value="">All currencies</option>{currencies.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Order status<select value={orderStatus} onChange={(event) => setOrderStatus(event.target.value)}><option value="">All statuses</option>{FULFILLMENT_ORDER_STATUSES.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><button type="button" className="admin-secondary-action" onClick={clearFilters}>Clear filters</button></div></section>
    <section className="financial-summary"><div className="financial-heading"><div><span>FINANCIAL DASHBOARD</span><h3>Revenue, cost, fees and profit</h3><p>Totals use the filtered immutable snapshots, while refund totals use append-only refund events. For mixed currencies, filter to one currency before interpreting total amounts.</p></div><BarChart3 size={20} /></div>{dashboardQuery.isLoading ? <div className="financial-loading"><Loader2 className="spin" size={18} /> Loading protected financial history…</div> : <div className="financial-metric-grid"><article><span>Gross revenue</span><strong>{money(summary?.grossRevenue)}</strong><small>Customer selling price</small></article><article><span>Supplier cost</span><strong>{money(summary?.supplierCost)}</strong><small>Converted snapshot cost</small></article><article><span>Gross profit</span><strong>{money(summary?.grossProfit)}</strong><small>Revenue less supplier cost</small></article><article><span>Payment fees</span><strong>{money(summary?.paymentFees)}</strong><small>Configured fees only</small></article><article><span>Refunds</span><strong>{money(summary?.refunds)}</strong><small>Recorded financial events</small></article><article><span>Net revenue</span><strong>{money(summary?.netRevenue)}</strong><small>After refunds</small></article><article className={(summary?.netProfit ?? 0) < 0 ? "negative" : "positive"}><span>Net profit</span><strong>{money(summary?.netProfit)}</strong><small>After cost, fees and refunds</small></article><article className={(summary?.profitMarginPercent ?? 0) < 0 ? "negative" : "positive"}><span>Profit margin</span><strong>{(summary?.profitMarginPercent ?? 0).toFixed(2)}%</strong><small>Net profit / gross revenue</small></article></div>}</section>
    <section className="financial-order-counts"><article><WalletCards size={18} /><div><span>Financial records</span><strong>{dashboard?.orders.total ?? 0}</strong></div></article><article><TrendingDown size={18} /><div><span>Completed orders</span><strong>{dashboard?.orders.completed ?? 0}</strong></div></article><article><AlertTriangle size={18} /><div><span>Failed / refunded</span><strong>{(dashboard?.orders.failed ?? 0) + (dashboard?.orders.refunded ?? 0)}</strong></div></article><article><Calculator size={18} /><div><span>Test-only records</span><strong>{dashboard?.orders.simulated ?? 0}</strong></div></article></section>
    <section className="financial-preview"><div className="financial-heading"><div><span>SERVER-BACKED PREVIEW</span><h3>Test a financial calculation before any future configuration</h3><p>This calculator performs no write and does not apply a price, fee, refund, or supplier-cost change.</p></div><Calculator size={20} /></div><div className="financial-preview-grid"><label>Customer selling price<input value={preview.selling} inputMode="decimal" onChange={(event) => updatePreview("selling", event.target.value)} /></label><label>Supplier cost<input value={preview.supplier} inputMode="decimal" onChange={(event) => updatePreview("supplier", event.target.value)} /></label><label>Exchange rate<input value={preview.rate} inputMode="decimal" onChange={(event) => updatePreview("rate", event.target.value)} /></label><label>Converted supplier cost<input value={preview.converted} inputMode="decimal" onChange={(event) => updatePreview("converted", event.target.value)} /></label><label>Payment processing fee<input value={preview.processingFee} inputMode="decimal" onChange={(event) => updatePreview("processingFee", event.target.value)} /></label><label>Other applicable fee<input value={preview.otherFee} inputMode="decimal" onChange={(event) => updatePreview("otherFee", event.target.value)} /></label><label>Refund amount<input value={preview.refund} inputMode="decimal" onChange={(event) => updatePreview("refund", event.target.value)} /></label><label className="financial-check"><input type="checkbox" checked={preview.feeConfigured} onChange={(event) => updatePreview("feeConfigured", event.target.checked)} /> Payment fee is configured</label><button type="button" className="admin-primary-action" onClick={() => setPreviewRequested(true)}>Calculate preview</button></div>{previewRequested && (previewQuery.isLoading ? <div className="financial-loading"><Loader2 className="spin" size={18} /> Calculating on the server…</div> : previewQuery.data ? <div className="financial-preview-result"><span>Gross revenue <strong>{money(previewQuery.data.grossRevenue)}</strong></span><span>Gross profit <strong>{money(previewQuery.data.grossProfit)}</strong></span><span>Net revenue <strong>{money(previewQuery.data.netRevenue)}</strong></span><span>Net profit <strong>{money(previewQuery.data.netProfit)}</strong></span><span>Profit margin <strong>{previewQuery.data.profitMarginPercent.toFixed(2)}%</strong></span><p>{previewQuery.data.note}</p></div> : <p className="financial-empty">Preview could not be calculated. Check the values and try again.</p>)}</section>
    <section className="financial-alerts"><div className="financial-heading"><div><span>FINANCIAL ALERTS</span><h3>Review before acting</h3><p>Alerts are diagnostic only. They never modify pricing, supplier costs, orders, wallets, transactions, or refunds.</p></div><AlertTriangle size={20} /></div>{!alerts.length ? <p className="financial-empty">No financial alert exists because no financial snapshot has been created. No alert record is fabricated.</p> : <div className="financial-alert-grid">{alerts.map((alert, index) => <article key={`${alert.snapshotId}-${alert.type}-${index}`}><AlertTriangle size={16} /><div><strong>{label(alert.type)}</strong><span>{alert.productName} · {alert.orderReference}</span><small>Supplier {alert.supplierKey || "not selected"} · margin {alert.profitMarginPercent.toFixed(2)}% · {new Date(alert.createdAt).toLocaleString()}</small></div></article>)}</div>}</section>
    <section className="financial-rollups"><FinancialRollup title="Product profitability" rows={(rollups?.products ?? []) as ProfitRow[]} /><FinancialRollup title="Category profitability" rows={(rollups?.categories ?? []) as ProfitRow[]} /><FinancialRollup title="Supplier profitability" rows={(rollups?.suppliers ?? []) as ProfitRow[]} /></section>
    <section className="financial-records"><div className="financial-heading"><div><span>IMMUTABLE FINANCIAL SNAPSHOTS</span><h3>Historical snapshot records</h3><p>Each row is server-derived. Future supplier, exchange-rate, pricing, or fee changes do not overwrite it.</p></div><ShieldCheck size={20} /></div>{!records.length ? <p className="financial-empty">No financial snapshot exists. Existing orders were not modified or backfilled.</p> : <div className="admin-table-wrap"><table><thead><tr><th>Reference</th><th>Product / supplier</th><th>Selling price</th><th>Supplier cost</th><th>Fees</th><th>Net profit</th><th>Margin</th><th>Status</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><strong>{record.orderReference}</strong><small>{new Date(record.createdAt).toLocaleString()}</small></td><td>{record.productName}<small>{record.supplierKey || "No supplier selected"}</small></td><td>{money(record.customerSellingPrice, record.customerCurrency)}</td><td>{record.supplierCostInCustomerCurrency === null ? "Missing" : money(record.supplierCostInCustomerCurrency, record.customerCurrency)}</td><td>{money(record.paymentProcessingFee + record.otherApplicableFees, record.customerCurrency)}</td><td>{money(record.netProfit, record.customerCurrency)}</td><td>{record.profitMarginPercent.toFixed(2)}%</td><td><span className="financial-status">{label(record.orderStatus)}</span></td></tr>)}</tbody></table></div>}</section>
  </section>;
}

function FinancialRollup({ title, rows }: { title: string; rows: ProfitRow[] }) {
  return <article className="financial-rollup"><h3>{title}</h3>{!rows.length ? <p>No immutable financial snapshot yet.</p> : <div className="admin-table-wrap"><table><thead><tr><th>Scope</th><th>Records</th><th>Revenue</th><th>Cost</th><th>Fees</th><th>Net profit</th><th>Margin</th></tr></thead><tbody>{rows.map((row) => <tr key={row.key}><td>{label(row.label)}</td><td>{row.records}</td><td>{money(row.grossRevenue)}</td><td>{money(row.supplierCost)}</td><td>{money(row.paymentFees)}</td><td>{money(row.netProfit)}</td><td>{row.profitMarginPercent.toFixed(2)}%</td></tr>)}</tbody></table></div>}</article>;
}
