import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, CircleDollarSign, Clock3, FileWarning, RefreshCw, RotateCcw, Search, ShieldCheck, WalletCards } from "lucide-react";
import { useDeferredValue, useMemo, useState } from "react";
import { toast } from "sonner";
import "./adminWebhookTopUpControl.css";

type View = "transactions" | "webhooks" | "reconciliation" | "timeline" | "audit";
type Filters = { search: string; status: string; provider: string; currency: string; category: string; start: string; end: string };

const VIEW_LABELS: Record<View, string> = {
  transactions: "Top-up transactions",
  webhooks: "Webhook monitor",
  reconciliation: "Reconciliation",
  timeline: "Wallet timeline",
  audit: "Audit logs",
};

function money(amount: number | null | undefined, currency?: string | null) {
  if (amount === null || amount === undefined) return "—";
  return new Intl.NumberFormat(undefined, { style: "currency", currency: currency || "USD", maximumFractionDigits: 2 }).format(amount);
}

function label(value: string | null | undefined) {
  return (value || "unavailable").replaceAll("_", " ");
}

function statusClass(status: string | null | undefined) {
  if (["settled", "completed", "verified", "credited", "resolved", "reconciled", "successful"].includes(status || "")) return "success";
  if (["failed", "error", "invalid", "duplicate", "rejected", "reversed"].includes(status || "")) return "danger";
  return "warning";
}

function dateValue(value: Date | string | null | undefined) {
  return value ? new Date(value).toLocaleString() : "—";
}

function formatCurrencyTotals(rows: Array<{ currency: string; amount: number }> | undefined) {
  return rows?.length ? rows.map((row) => money(row.amount, row.currency)).join(" · ") : "No credited amount";
}

export function AdminWebhookTopUpControl() {
  const [view, setView] = useState<View>("transactions");
  const [filters, setFilters] = useState<Filters>({ search: "", status: "", provider: "", currency: "", category: "", start: "", end: "" });
  const [offsets, setOffsets] = useState<Record<View, number>>({ transactions: 0, webhooks: 0, reconciliation: 0, timeline: 0, audit: 0 });
  const [selectedFundingCode, setSelectedFundingCode] = useState<string | null>(null);
  const [fundingReview, setFundingReview] = useState({ action: "settle" as "settle" | "reject", verificationReference: "", reviewNote: "" });
  const [selectedCaseId, setSelectedCaseId] = useState<number | null>(null);
  const [resolutionNote, setResolutionNote] = useState("");
  const [adjustment, setAdjustment] = useState({ email: "", direction: "credit" as "credit" | "debit", amount: "", currency: "USD", reference: "", reason: "", confirmation: "" });
  const [reversal, setReversal] = useState({ walletEntryId: "", reference: "", reason: "", confirmation: "" });
  const deferredSearch = useDeferredValue(filters.search.trim());
  const pageInput = useMemo(() => ({ search: deferredSearch || undefined, provider: filters.provider || undefined, currency: filters.currency || undefined, start: filters.start ? new Date(`${filters.start}T00:00:00`) : undefined, end: filters.end ? new Date(`${filters.end}T23:59:59`) : undefined, offset: offsets[view], limit: 50 }), [deferredSearch, filters.currency, filters.end, filters.provider, filters.start, offsets, view]);
  const dashboard = trpc.admin.getTopUpControlDashboard.useQuery();
  const integrations = trpc.admin.listCommerceIntegrations.useQuery();
  const transactions = trpc.admin.listTopUpTransactions.useQuery({ ...pageInput, status: view === "transactions" && filters.status ? filters.status as "initialized" | "pending" | "settled" | "failed" | "expired" | "cancelled" | "reversed" : undefined }, { enabled: view === "transactions" });
  const webhooks = trpc.admin.listTopUpWebhookMonitor.useQuery({ ...pageInput, status: view === "webhooks" && filters.status ? filters.status as "received" | "verified" | "credited" | "duplicate" | "rejected" | "error" | "reconciled" : undefined }, { enabled: view === "webhooks" });
  const cases = trpc.admin.listTopUpReconciliationCases.useQuery({ ...pageInput, status: view === "reconciliation" && filters.status ? filters.status as "open" | "resolved" : undefined, category: view === "reconciliation" && filters.category ? filters.category as "missing_wallet_credit" | "duplicate_event" | "duplicate_reference" | "invalid_signature" | "amount_currency_mismatch" | "provider_failed" | "provider_pending" | "refunded_or_reversed" : undefined }, { enabled: view === "reconciliation" });
  const timeline = trpc.admin.listUserWalletTimeline.useQuery({ ...pageInput, status: view === "timeline" && filters.status ? filters.status as "pending" | "completed" | "reversed" | "failed" : undefined, category: view === "timeline" && filters.category ? filters.category as "funding" | "purchase" | "refund" | "adjustment" | "reward" : undefined }, { enabled: view === "timeline" });
  const audits = trpc.admin.listTopUpControlAudit.useQuery(pageInput, { enabled: view === "audit" });
  const utils = trpc.useUtils();
  const refresh = async () => {
    await Promise.all([
      dashboard.refetch(),
      transactions.refetch(),
      webhooks.refetch(),
      cases.refetch(),
      timeline.refetch(),
      audits.refetch(),
    ]);
  };
  const reviewFunding = trpc.admin.reviewWalletFundingRequest.useMutation({ onSuccess: async (result) => { toast.success(`Top-up ${result.status}.`); setSelectedFundingCode(null); setFundingReview({ action: "settle", verificationReference: "", reviewNote: "" }); await refresh(); }, onError: (error) => toast.error(error.message) });
  const resolveCase = trpc.admin.resolveTopUpReconciliationCase.useMutation({ onSuccess: async () => { toast.success("Reconciliation case marked resolved."); setSelectedCaseId(null); setResolutionNote(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  const createAdjustment = trpc.admin.createManualWalletAdjustment.useMutation({ onSuccess: async () => { toast.success("Immutable wallet adjustment recorded."); setAdjustment({ email: "", direction: "credit", amount: "", currency: "USD", reference: "", reason: "", confirmation: "" }); await refresh(); }, onError: (error) => toast.error(error.message) });
  const reverseEntry = trpc.admin.reverseWalletLedgerEntry.useMutation({ onSuccess: async () => { toast.success("Compensating wallet reversal recorded."); setReversal({ walletEntryId: "", reference: "", reason: "", confirmation: "" }); await refresh(); }, onError: (error) => toast.error(error.message) });
  const paymentIntegrations = (integrations.data ?? []).filter((item) => item.integrationType === "payment");
  const activeData = view === "transactions" ? transactions.data : view === "webhooks" ? webhooks.data : view === "reconciliation" ? cases.data : view === "timeline" ? timeline.data : audits.data;
  const loading = view === "transactions" ? transactions.isLoading : view === "webhooks" ? webhooks.isLoading : view === "reconciliation" ? cases.isLoading : view === "timeline" ? timeline.isLoading : audits.isLoading;
  const setFilter = <K extends keyof Filters>(key: K, value: Filters[K]) => { setFilters((current) => ({ ...current, [key]: value })); setOffsets((current) => ({ ...current, [view]: 0 })); };
  const statusOptions = view === "transactions" ? ["initialized", "pending", "settled", "failed", "expired", "cancelled", "reversed"] : view === "webhooks" ? ["received", "verified", "credited", "duplicate", "rejected", "error", "reconciled"] : view === "reconciliation" ? ["open", "resolved"] : view === "timeline" ? ["pending", "completed", "reversed", "failed"] : [];
  const categoryOptions = view === "reconciliation" ? ["missing_wallet_credit", "duplicate_event", "duplicate_reference", "invalid_signature", "amount_currency_mismatch", "provider_failed", "provider_pending", "refunded_or_reversed"] : view === "timeline" ? ["funding", "purchase", "refund", "adjustment", "reward"] : [];

  return <section className="admin-webhook-topup-control">
    <header className="admin-panel admin-webhook-topup-hero">
      <div><span>SUPER ADMIN / PAYMENT SAFETY</span><h2>Webhook / Top-Up Control</h2><p>Monitor redacted provider receipts, reconcile wallet funding, and create only immutable ledger entries. Provider credentials, raw webhook payloads, and signature material never enter this workspace.</p></div>
      <button type="button" className="admin-secondary-action" onClick={() => void refresh()} disabled={loading}><RefreshCw size={15} /> Refresh data</button>
    </header>

    {!paymentIntegrations.length && <div className="admin-policy-note admin-webhook-provider-notice"><ShieldCheck size={16} /><span><strong>No payment provider is configured.</strong> The monitor and reconciliation controls are live for recorded wallet requests and future verified webhook receipts, but no provider callback can create a credit until a payment integration and server-only webhook verification are configured.</span></div>}

    <section className="admin-metric-grid admin-webhook-topup-metrics">
      <article><WalletCards size={19} /><span>TOTAL TOP-UPS</span><strong>{dashboard.data?.totalTopUps ?? "—"}</strong><small>Recorded wallet funding attempts</small></article>
      <article><CheckCircle2 size={19} /><span>SUCCESSFUL</span><strong>{dashboard.data?.successful ?? "—"}</strong><small>{formatCurrencyTotals(dashboard.data?.creditedByCurrency)} credited through immutable funding entries</small></article>
      <article><Clock3 size={19} /><span>PENDING</span><strong>{dashboard.data?.pending ?? "—"}</strong><small>Need verified review before any credit</small></article>
      <article><FileWarning size={19} /><span>FAILED / REVERSED</span><strong>{dashboard.data ? dashboard.data.failed + dashboard.data.reversed : "—"}</strong><small>{dashboard.data?.reversed ?? 0} reversals recorded</small></article>
      <article><AlertTriangle size={19} /><span>SUSPICIOUS</span><strong>{dashboard.data?.suspicious ?? "—"}</strong><small>Invalid, duplicate, or errored receipts</small></article>
      <article><CircleDollarSign size={19} /><span>UNRESOLVED</span><strong>{dashboard.data?.unresolvedWebhookErrors ?? "—"}</strong><small>{formatCurrencyTotals(dashboard.data?.receivedByCurrency)} received / verified funding amount</small></article>
    </section>

    <section className="admin-panel admin-webhook-topup-list">
      <header><div><span>CONTROL LEDGER</span><h2>{VIEW_LABELS[view]}</h2><p>Search user, email, username, event ID, transaction/reference ID, or funding code. Results are server-filtered and limited to 50 entries per page.</p></div><Search size={19} /></header>
      <div className="admin-webhook-topup-tabs" role="tablist" aria-label="Webhook and wallet-control views">{(Object.keys(VIEW_LABELS) as View[]).map((item) => <button type="button" key={item} role="tab" aria-selected={view === item} className={view === item ? "admin-primary-action" : "admin-secondary-action"} onClick={() => { setView(item); setOffsets((current) => ({ ...current, [item]: 0 })); }}>{VIEW_LABELS[item]}</button>)}</div>
      <div className="admin-webhook-topup-filters">
        <label>Search<input value={filters.search} onChange={(event) => setFilter("search", event.target.value)} placeholder="User, email, reference or event" /></label>
        <label>Status<select value={filters.status} onChange={(event) => setFilter("status", event.target.value)}><option value="">All statuses</option>{statusOptions.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label>
        <label>Provider<input value={filters.provider} onChange={(event) => setFilter("provider", event.target.value)} placeholder="Configured provider" /></label>
        <label>Currency<select value={filters.currency} onChange={(event) => setFilter("currency", event.target.value)}><option value="">All currencies</option><option value="USD">USD</option><option value="NGN">NGN</option><option value="EUR">EUR</option><option value="GBP">GBP</option></select></label>
        {categoryOptions.length > 0 && <label>Category<select value={filters.category} onChange={(event) => setFilter("category", event.target.value)}><option value="">All categories</option>{categoryOptions.map((category) => <option key={category} value={category}>{label(category)}</option>)}</select></label>}
        <label>From<input type="date" value={filters.start} onChange={(event) => setFilter("start", event.target.value)} /></label>
        <label>To<input type="date" value={filters.end} onChange={(event) => setFilter("end", event.target.value)} /></label>
      </div>
      {loading ? <p className="admin-empty">Loading protected records…</p> : view === "transactions" ? <TransactionTable rows={transactions.data?.transactions ?? []} onReview={(fundingCode) => { setSelectedFundingCode(fundingCode); setFundingReview({ action: "settle", verificationReference: "", reviewNote: "" }); }} /> : view === "webhooks" ? <WebhookTable rows={webhooks.data?.events ?? []} /> : view === "reconciliation" ? <ReconciliationTable rows={cases.data?.cases ?? []} onResolve={(caseId) => { setSelectedCaseId(caseId); setResolutionNote(""); }} /> : view === "timeline" ? <TimelineTable rows={timeline.data?.entries ?? []} onReverse={(entryId) => setReversal({ walletEntryId: String(entryId), reference: "", reason: "", confirmation: "" })} /> : <AuditTable rows={audits.data?.audits ?? []} />}
      <div className="admin-webhook-topup-pagination"><button type="button" className="admin-secondary-action" disabled={offsets[view] === 0} onClick={() => setOffsets((current) => ({ ...current, [view]: Math.max(0, current[view] - 50) }))}>Previous</button><span>Showing {offsets[view] + 1}–{offsets[view] + 50}</span><button type="button" className="admin-secondary-action" disabled={!activeData?.hasMore} onClick={() => setOffsets((current) => ({ ...current, [view]: current[view] + 50 }))}>Next</button></div>
    </section>

    {selectedFundingCode && <section className="admin-panel admin-webhook-topup-action"><header><div><span>PAYMENT VERIFICATION</span><h2>Review top-up {selectedFundingCode}</h2><p>Settling creates one immutable funding ledger credit only after you confirm the amount, currency, provider reference, and provider result outside this dashboard. Duplicate or unresolved blocking cases cannot be credited.</p></div><button type="button" className="admin-secondary-action" onClick={() => setSelectedFundingCode(null)}>Close</button></header><form onSubmit={(event) => { event.preventDefault(); reviewFunding.mutate({ fundingCode: selectedFundingCode, action: fundingReview.action, verificationReference: fundingReview.verificationReference || undefined, reviewNote: fundingReview.reviewNote || undefined }); }}><div className="admin-form-split"><label>Decision<select value={fundingReview.action} onChange={(event) => setFundingReview((current) => ({ ...current, action: event.target.value as "settle" | "reject" }))}><option value="settle">Settle verified top-up</option><option value="reject">Reject top-up</option></select></label><label>Provider transaction/reference<input value={fundingReview.verificationReference} required={fundingReview.action === "settle"} onChange={(event) => setFundingReview((current) => ({ ...current, verificationReference: event.target.value }))} placeholder="Verified external reference" /></label></div><label>Verification or rejection note<textarea value={fundingReview.reviewNote} onChange={(event) => setFundingReview((current) => ({ ...current, reviewNote: event.target.value }))} placeholder="State the verification outcome and evidence reviewed" /></label><button type="submit" className="admin-primary-action" disabled={reviewFunding.isPending}>{reviewFunding.isPending ? "Recording…" : fundingReview.action === "settle" ? "Confirm verified wallet credit" : "Confirm rejection"}</button></form></section>}

    {selectedCaseId && <section className="admin-panel admin-webhook-topup-action"><header><div><span>RECONCILIATION RESOLUTION</span><h2>Close discrepancy case</h2><p>Closing a case preserves its original receipt and discrepancy record. This action does not credit, debit, or overwrite any wallet.</p></div><button type="button" className="admin-secondary-action" onClick={() => setSelectedCaseId(null)}>Close</button></header><form onSubmit={(event) => { event.preventDefault(); resolveCase.mutate({ caseId: selectedCaseId, resolutionNote }); }}><label>Resolution note<textarea required minLength={3} value={resolutionNote} onChange={(event) => setResolutionNote(event.target.value)} placeholder="Record the verified reconciliation outcome" /></label><button type="submit" className="admin-primary-action" disabled={resolveCase.isPending}>{resolveCase.isPending ? "Resolving…" : "Mark case resolved"}</button></form></section>}

    <section className="admin-webhook-topup-actions">
      <section className="admin-panel admin-webhook-topup-action"><header><div><span>MANUAL WALLET ADJUSTMENT</span><h2>Credit or debit by ledger entry</h2><p>This never overwrites a balance. A customer email, unique reference, reason, typed confirmation, balance snapshot, and immutable Admin audit record are required.</p></div><WalletCards size={19} /></header><form onSubmit={(event) => { event.preventDefault(); createAdjustment.mutate({ email: adjustment.email, direction: adjustment.direction, amount: Number(adjustment.amount), currency: adjustment.currency, reference: adjustment.reference, reason: adjustment.reason, confirmation: adjustment.confirmation as "CONFIRM WALLET ADJUSTMENT" }); }}><div className="admin-form-split"><label>Customer email<input type="email" required value={adjustment.email} onChange={(event) => setAdjustment((current) => ({ ...current, email: event.target.value }))} placeholder="customer@example.com" /></label><label>Direction<select value={adjustment.direction} onChange={(event) => setAdjustment((current) => ({ ...current, direction: event.target.value as "credit" | "debit" }))}><option value="credit">Credit</option><option value="debit">Debit</option></select></label><label>Amount<input type="number" min="0.01" step="0.01" required value={adjustment.amount} onChange={(event) => setAdjustment((current) => ({ ...current, amount: event.target.value }))} /></label><label>Currency<input required maxLength={3} value={adjustment.currency} onChange={(event) => setAdjustment((current) => ({ ...current, currency: event.target.value.toUpperCase() }))} /></label></div><label>Unique reference<input required value={adjustment.reference} onChange={(event) => setAdjustment((current) => ({ ...current, reference: event.target.value }))} placeholder="e.g. ADMIN-2026-0001" /></label><label>Reason<textarea required minLength={3} value={adjustment.reason} onChange={(event) => setAdjustment((current) => ({ ...current, reason: event.target.value }))} /></label><label>Type confirmation<input required value={adjustment.confirmation} onChange={(event) => setAdjustment((current) => ({ ...current, confirmation: event.target.value }))} placeholder="CONFIRM WALLET ADJUSTMENT" /></label><button type="submit" className="admin-danger-action" disabled={createAdjustment.isPending}>{createAdjustment.isPending ? "Recording…" : "Record immutable adjustment"}</button></form></section>
      <section className="admin-panel admin-webhook-topup-action"><header><div><span>REFUND / REVERSAL CONTROL</span><h2>Reverse one ledger entry</h2><p>Creates an opposite compensating entry and marks the original ledger entry reversed. The original cannot be deleted or reversed twice.</p></div><RotateCcw size={19} /></header><form onSubmit={(event) => { event.preventDefault(); reverseEntry.mutate({ walletEntryId: Number(reversal.walletEntryId), reference: reversal.reference, reason: reversal.reason, confirmation: reversal.confirmation as "CONFIRM WALLET REVERSAL" }); }}><label>Wallet ledger entry ID<input type="number" min="1" required value={reversal.walletEntryId} onChange={(event) => setReversal((current) => ({ ...current, walletEntryId: event.target.value }))} /></label><label>Unique reversal reference<input required value={reversal.reference} onChange={(event) => setReversal((current) => ({ ...current, reference: event.target.value }))} placeholder="e.g. REVERSAL-2026-0001" /></label><label>Reason<textarea required minLength={3} value={reversal.reason} onChange={(event) => setReversal((current) => ({ ...current, reason: event.target.value }))} /></label><label>Type confirmation<input required value={reversal.confirmation} onChange={(event) => setReversal((current) => ({ ...current, confirmation: event.target.value }))} placeholder="CONFIRM WALLET REVERSAL" /></label><button type="submit" className="admin-danger-action" disabled={reverseEntry.isPending}>{reverseEntry.isPending ? "Recording…" : "Record compensating reversal"}</button></form></section>
    </section>
  </section>;
}

function TransactionTable({ rows, onReview }: { rows: Array<any>; onReview: (fundingCode: string) => void }) { return <div className="admin-table-wrap"><table><thead><tr><th>User</th><th>Previous balance</th><th>Credited amount</th><th>Current balance</th><th>Method / provider ID</th><th>Status</th><th>Time</th><th>Control</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><strong>{row.customerUsername || row.customerName || `User #${row.userId}`}</strong><small>{row.customerEmail || "Email unavailable"}</small></td><td>{row.previousBalance === null ? "Not credited" : money(row.previousBalance, row.currency)}</td><td>{money(row.amount, row.currency)}</td><td>{row.resultingBalance === null ? money(row.currentBalance, row.currency) : money(row.resultingBalance, row.currency)}</td><td><strong>{row.paymentMethod}</strong><small>{row.providerReference || row.fundingCode}</small></td><td><span className={`admin-status ${statusClass(row.status)}`}>{label(row.status)}</span></td><td>{dateValue(row.settledAt || row.createdAt)}</td><td>{row.status === "pending" || row.status === "initialized" ? <button type="button" className="admin-secondary-action" onClick={() => onReview(row.fundingCode)}>Review</button> : "—"}</td></tr>) : <tr><td colSpan={8}>No recorded top-up transactions match these filters.</td></tr>}</tbody></table></div>; }
function WebhookTable({ rows }: { rows: Array<any> }) { return <div className="admin-table-wrap"><table><thead><tr><th>Provider</th><th>Event ID</th><th>Transaction / reference</th><th>User</th><th>Amount</th><th>Event</th><th>Signature</th><th>Status / error</th><th>Date/time</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td>{row.provider}</td><td>{row.eventId}</td><td><strong>{row.transactionId || "—"}</strong><small>{row.reference || row.fundingCode || "No linked reference"}</small></td><td><strong>{row.customerUsername || row.customerName || (row.userId ? `User #${row.userId}` : "Unlinked")}</strong><small>{row.customerEmail || "—"}</small></td><td>{money(row.amount, row.currency)}</td><td>{label(row.eventType)}</td><td><span className={`admin-status ${statusClass(row.signatureStatus)}`}>{label(row.signatureStatus)}</span></td><td><span className={`admin-status ${statusClass(row.status)}`}>{label(row.status)}</span><small>{row.errorMessage || label(row.providerStatus)}</small></td><td>{dateValue(row.receivedAt)}</td></tr>) : <tr><td colSpan={9}>No payment webhook receipts match these filters. No raw payloads or secrets are displayed.</td></tr>}</tbody></table></div>; }
function ReconciliationTable({ rows, onResolve }: { rows: Array<any>; onResolve: (caseId: number) => void }) { return <div className="admin-table-wrap"><table><thead><tr><th>Case</th><th>Category</th><th>Provider / event</th><th>User</th><th>Detail</th><th>Status</th><th>Date/time</th><th>Control</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><strong>{row.caseKey}</strong><small>{row.fundingCode || "No linked funding request"}</small></td><td>{label(row.category)}</td><td><strong>{row.provider || "—"}</strong><small>{row.eventId || row.providerStatus || "—"}</small></td><td><strong>{row.customerUsername || row.customerName || (row.userId ? `User #${row.userId}` : "Unlinked")}</strong><small>{row.customerEmail || "—"}</small></td><td>{row.detail}<small>{row.resolutionNote || ""}</small></td><td><span className={`admin-status ${statusClass(row.status)}`}>{label(row.status)}</span></td><td>{dateValue(row.resolvedAt || row.createdAt)}</td><td>{row.status === "open" ? <button type="button" className="admin-secondary-action" onClick={() => onResolve(row.id)}>Resolve</button> : "—"}</td></tr>) : <tr><td colSpan={8}>No payment discrepancies match these filters.</td></tr>}</tbody></table></div>; }
function TimelineTable({ rows, onReverse }: { rows: Array<any>; onReverse: (entryId: number) => void }) { return <div className="admin-table-wrap"><table><thead><tr><th>User</th><th>Activity</th><th>Amount</th><th>Balance change</th><th>Reference</th><th>Status</th><th>Date/time</th><th>Control</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><strong>{row.customerUsername || row.customerName || `User #${row.userId}`}</strong><small>{row.customerEmail || "—"}</small></td><td>{label(row.entryType)} · {label(row.direction)}</td><td>{money(row.amount, row.currency)}</td><td>{row.previousBalance === null ? "Snapshot unavailable" : `${money(row.previousBalance, row.currency)} → ${money(row.resultingBalance, row.currency)}`}</td><td>{row.reference}</td><td><span className={`admin-status ${statusClass(row.status)}`}>{label(row.status)}</span></td><td>{dateValue(row.createdAt)}</td><td>{row.status === "completed" && !row.reversedAt ? <button type="button" className="admin-secondary-action" onClick={() => onReverse(row.id)}>Reverse</button> : "—"}</td></tr>) : <tr><td colSpan={8}>No wallet ledger entries match these filters.</td></tr>}</tbody></table></div>; }
function AuditTable({ rows }: { rows: Array<any> }) { return <div className="admin-table-wrap"><table><thead><tr><th>Admin</th><th>Action</th><th>Target / reference</th><th>Summary</th><th>Date/time</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><strong>{row.adminName || `Admin #${row.adminUserId}`}</strong><small>{row.adminEmail || "—"}</small></td><td>{label(row.action)}</td><td>{row.targetType}<small>{row.targetId}</small></td><td>{row.summary}</td><td>{dateValue(row.createdAt)}</td></tr>) : <tr><td colSpan={5}>No wallet-control audit records match these filters.</td></tr>}</tbody></table></div>; }
