import { trpc } from "@/lib/trpc";
import { ADMIN_AUTH_FACTOR_STATES, displayOwnerName } from "@shared/adminAuthentication";
import { BellRing, CheckCircle2, CircleHelp, KeyRound, LockKeyhole, LogOut, MailCheck, MonitorSmartphone, Phone, RefreshCw, Save, ShieldAlert, ShieldCheck, Smartphone, UserRoundCog } from "lucide-react";
import { type FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type SettingsSection = "profile" | "protection" | "notifications" | "sessions" | "recovery";

type ProfileDraft = { firstName: string; lastName: string; username: string; phone: string; countryCode: string };

const emptyDraft: ProfileDraft = { firstName: "", lastName: "", username: "", phone: "", countryCode: "" };

export function AdminAuthenticationSettings({ onSignOut }: { onSignOut: () => void }) {
  const utils = trpc.useUtils();
  const [section, setSection] = useState<SettingsSection>("profile");
  const [profileDraft, setProfileDraft] = useState<ProfileDraft>(emptyDraft);
  const dashboard = trpc.marketplace.customerDashboard.useQuery();
  const currentUser = trpc.auth.me.useQuery();
  const preferences = dashboard.data?.notificationPreferences;
  const saveProfile = trpc.marketplace.updateCustomerProfile.useMutation({
    onSuccess: async () => { toast.success("Owner profile details saved."); await utils.marketplace.customerDashboard.invalidate(); },
    onError: (error) => toast.error(error.message || "Could not save owner profile details."),
  });
  const savePreferences = trpc.marketplace.updateNotificationPreferences.useMutation({
    onSuccess: async () => { toast.success("Security-alert preference saved."); await utils.marketplace.customerDashboard.invalidate(); },
    onError: (error) => toast.error(error.message || "Could not save the security-alert preference."),
  });

  useEffect(() => {
    const profile = dashboard.data?.profile;
    if (!profile) return;
    setProfileDraft({ firstName: profile.firstName || "", lastName: profile.lastName || "", username: profile.username || "", phone: profile.phone || "", countryCode: profile.countryCode || "" });
  }, [dashboard.data?.profile]);

  const ownerName = displayOwnerName(dashboard.data?.profile, currentUser.data?.name);
  const securityEvents = dashboard.data?.securityEvents ?? [];
  const sectionButton = (id: SettingsSection, label: string, Icon: typeof UserRoundCog) => <button type="button" onClick={() => setSection(id)} className={`flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-xs font-semibold transition ${section === id ? "bg-[#eaf0ff] text-[#286dff]" : "text-slate-600 hover:bg-slate-100"}`}><Icon size={15} />{label}</button>;
  const saveOwnerProfile = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!window.confirm("Save these owner profile details? Your provider-managed sign-in email is not changed.")) return;
    saveProfile.mutate({ firstName: profileDraft.firstName.trim() || null, lastName: profileDraft.lastName.trim() || null, username: profileDraft.username.trim() || null, phone: profileDraft.phone.trim() || null, countryCode: profileDraft.countryCode.trim().toUpperCase() || null, registrationSource: null });
  };
  const setSecurityAlerts = (next: boolean) => {
    if (!preferences) return;
    savePreferences.mutate({ orderUpdates: preferences.orderUpdates, paymentUpdates: preferences.paymentUpdates, walletUpdates: preferences.walletUpdates, marketingUpdates: preferences.marketingUpdates, productAnnouncements: preferences.productAnnouncements, securityAlerts: next });
  };
  const verifiedEmail = Boolean(currentUser.data?.email && dashboard.data?.profile?.accountStatus !== "pending_email_verification") ? "Provider-managed" : "Not available";

  return <section className="admin-panel overflow-hidden"><header><div><span>SETTINGS · AUTHENTICATION</span><h2>Owner account & sign-in security</h2><p>Manage the profile and protection settings VAMNUX can safely store today. Provider-managed identity remains the active sign-in route; no email code, phone code, authenticator, recovery code, or all-device revocation is presented as active until it is configured and enforced server-side.</p></div><LockKeyhole size={21} /></header>
    <section className="admin-metric-grid"><article><span>OWNER ACCESS</span><strong>Protected</strong><small>Role and server email allowlist</small></article><article><span>IDENTITY EMAIL</span><strong className="text-[20px]">{verifiedEmail}</strong><small>{currentUser.data?.email || "Email unavailable"}</small></article><article><span>SECURITY ALERTS</span><strong>{preferences?.securityAlerts ? "On" : "Off"}</strong><small>Stored preference for VAMNUX account alerts</small></article><article><span>AUTHENTICATOR</span><strong>Not enrolled</strong><small>Enrollment flow not configured</small></article></section>
    <div className="grid gap-0 border-t border-white/10 xl:grid-cols-[220px_1fr]">
      <aside className="border-b border-white/10 bg-white/[.025] p-4 xl:border-b-0 xl:border-r"><p className="mb-3 px-3 text-[10px] font-extrabold tracking-[.12em] text-[#aeb9cd]">ACCOUNT SETTINGS</p>{sectionButton("profile", "General profile", UserRoundCog)}{sectionButton("protection", "Sign-in protection", LockKeyhole)}{sectionButton("notifications", "Security alerts", BellRing)}{sectionButton("sessions", "Current session", MonitorSmartphone)}{sectionButton("recovery", "Recovery readiness", KeyRound)}<div className="mt-5 rounded-lg border border-[#b8ff43]/20 bg-[#b8ff43]/5 p-3 text-[11px] leading-5 text-[#d7e0ef]"><ShieldCheck size={15} className="mb-2 text-[#b8ff43]" />Changing a profile field does not change the provider-owned sign-in email or weaken owner authorization.</div></aside>
      <div className="min-w-0 p-4 sm:p-6">
        {section === "profile" && <form onSubmit={saveOwnerProfile} className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="admin-form-kicker">GENERAL</p><h3 className="text-xl font-bold text-white">Owner profile</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-[#aeb9cd]">Use a clear owner display name and recovery contact number. A phone number is stored only as contact information until a verified phone challenge is configured.</p></div><span className="admin-status good">Owner only</span></div><div className="admin-form-split"><label>First name<input value={profileDraft.firstName} onChange={(event) => setProfileDraft({ ...profileDraft, firstName: event.target.value })} maxLength={80} placeholder="First name" /></label><label>Last name<input value={profileDraft.lastName} onChange={(event) => setProfileDraft({ ...profileDraft, lastName: event.target.value })} maxLength={80} placeholder="Last name" /></label><label>Username<input value={profileDraft.username} onChange={(event) => setProfileDraft({ ...profileDraft, username: event.target.value })} maxLength={30} placeholder="vamnux-owner" /></label><label>Country code<input value={profileDraft.countryCode} onChange={(event) => setProfileDraft({ ...profileDraft, countryCode: event.target.value.toUpperCase() })} maxLength={2} placeholder="NG" /></label></div><label>Recovery contact phone <small>not verified</small><input value={profileDraft.phone} onChange={(event) => setProfileDraft({ ...profileDraft, phone: event.target.value })} maxLength={32} inputMode="tel" placeholder="+234…" /></label><div className="admin-policy-note"><MailCheck size={15} /><span><strong>Provider-managed sign-in email:</strong> {currentUser.data?.email || "Unavailable"}. Email changes and verification must be completed in the current secure identity provider; VAMNUX does not overwrite provider identity data here.</span></div><button type="submit" className="admin-primary-action" disabled={saveProfile.isPending}>{saveProfile.isPending ? "Saving…" : "Save owner details"} <Save size={14} /></button></form>}
        {section === "protection" && <div className="space-y-5"><div><p className="admin-form-kicker">SIGN-IN PROTECTION</p><h3 className="text-xl font-bold text-white">Verification and challenge methods</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-[#aeb9cd]">Each factor requires server-side enrollment, verification, enforcement on every Admin sign-in, and tested recovery. The current secure OAuth session plus owner role/email enforcement remains active.</p></div><div className="grid gap-4 lg:grid-cols-3">{[{ key: "emailChallenge", Icon: MailCheck }, { key: "authenticator", Icon: Smartphone }, { key: "phone", Icon: Phone }].map(({ key, Icon }) => { const factor = ADMIN_AUTH_FACTOR_STATES[key as "emailChallenge" | "authenticator" | "phone"]; return <article key={key} className="rounded-xl border border-white/10 bg-[#0d111a] p-4"><Icon size={19} className="text-[#b8ff43]" /><p className="mt-3 font-bold text-white">{factor.title}</p><span className="admin-status muted mt-2">Not configured</span><p className="mt-3 text-xs leading-5 text-[#aeb9cd]">{factor.detail}</p><button type="button" disabled className="admin-secondary-action mt-4 cursor-not-allowed opacity-55">Setup unavailable</button></article>; })}</div><div className="admin-policy-note"><ShieldAlert size={15} /><span><strong>Admin login rule today:</strong> a valid secure-provider session, the `admin` role, and the server-side owner email allowlist are required. A second factor cannot be required until it is actually enrolled and verified.</span></div></div>}
        {section === "notifications" && <div className="space-y-5"><div><p className="admin-form-kicker">SECURITY ALERTS</p><h3 className="text-xl font-bold text-white">Owner notification preference</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-[#aeb9cd]">This setting stores your VAMNUX account preference. Email, SMS, and WhatsApp alert delivery remain unavailable until a verified sending channel is configured.</p></div><article className="flex flex-col gap-4 rounded-xl border border-white/10 bg-[#0d111a] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-white">Keep in-app security alerts enabled</p><p className="mt-1 text-sm leading-6 text-[#aeb9cd]">Security notices remain distinct from marketing messages and no external message is sent from this setting.</p></div><button type="button" role="switch" aria-checked={preferences?.securityAlerts ?? true} onClick={() => setSecurityAlerts(!(preferences?.securityAlerts ?? true))} disabled={!preferences || savePreferences.isPending} className={`rounded-full px-4 py-2 text-xs font-extrabold uppercase tracking-[.08em] ${preferences?.securityAlerts ?? true ? "bg-[#b8ff43] text-[#10121a]" : "border border-white/20 text-white"}`}>{savePreferences.isPending ? "Saving…" : preferences?.securityAlerts ? "Alerts on" : "Alerts off"}</button></article><div className="grid gap-4 md:grid-cols-2"><article className="rounded-xl border border-white/10 p-4"><p className="font-bold text-white">Email notifications</p><p className="mt-2 text-xs leading-5 text-[#aeb9cd]">Inactive until a transactional sender is configured and verified.</p></article><article className="rounded-xl border border-white/10 p-4"><p className="font-bold text-white">SMS / phone notifications</p><p className="mt-2 text-xs leading-5 text-[#aeb9cd]">Inactive until an SMS provider, verified phone, and rate-limited delivery flow are configured.</p></article></div></div>}
        {section === "sessions" && <div className="space-y-5"><div><p className="admin-form-kicker">SESSION CONTROL</p><h3 className="text-xl font-bold text-white">Current secure session</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-[#aeb9cd]">The active session was created by the configured identity provider. VAMNUX can securely clear this browser’s session on sign-out; provider-wide session revocation is not currently integrated.</p></div><article className="flex flex-col gap-4 rounded-xl border border-[#b8ff43]/25 bg-[#b8ff43]/5 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-white"><CheckCircle2 size={17} className="text-[#b8ff43]" /><strong>Current browser session</strong></div><p className="mt-2 text-sm leading-6 text-[#aeb9cd]">Signed in as {ownerName}. Last account sign-in: {currentUser.data?.lastSignedIn ? new Date(currentUser.data.lastSignedIn).toLocaleString() : "Unavailable"}.</p></div><button type="button" onClick={onSignOut} className="admin-danger-action"><LogOut size={14} />Sign out this browser</button></article><article className="rounded-xl border border-white/10 p-5"><p className="font-bold text-white">All-device sign-out</p><p className="mt-2 text-sm leading-6 text-[#aeb9cd]">{ADMIN_AUTH_FACTOR_STATES.allSessions.detail}</p><button type="button" disabled className="admin-secondary-action mt-4 cursor-not-allowed opacity-55">All-device sign-out unavailable</button></article></div>}
        {section === "recovery" && <div className="space-y-5"><div><p className="admin-form-kicker">RECOVERY & ACTIVITY</p><h3 className="text-xl font-bold text-white">Safe recovery readiness</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-[#aeb9cd]">Recovery codes are not created until an authenticator is securely enrolled. Never rely on an unverified phone number or a public inbox as an Admin recovery factor.</p></div><div className="grid gap-4 lg:grid-cols-2"><article className="rounded-xl border border-white/10 p-5"><KeyRound size={19} className="text-[#b8ff43]" /><p className="mt-3 font-bold text-white">Recovery codes</p><p className="mt-2 text-xs leading-5 text-[#aeb9cd]">Unavailable until protected authenticator enrollment and one-time recovery-code hashing are implemented.</p><button type="button" disabled className="admin-secondary-action mt-4 cursor-not-allowed opacity-55">Generate unavailable</button></article><article className="rounded-xl border border-white/10 p-5"><RefreshCw size={19} className="text-[#286dff]" /><p className="mt-3 font-bold text-white">Account recovery</p><p className="mt-2 text-xs leading-5 text-[#aeb9cd]">Use the current secure identity provider for account recovery. VAMNUX does not offer an unverified Admin reset path.</p></article></div><section className="rounded-xl border border-white/10"><div className="border-b border-white/10 px-5 py-4"><p className="font-bold text-white">Recent account security activity</p><p className="mt-1 text-xs text-[#aeb9cd]">Only your stored VAMNUX security-event summaries are shown. Device fingerprints, IP addresses, tokens, and secrets are excluded.</p></div>{dashboard.isLoading ? <p className="p-5 text-sm text-[#aeb9cd]">Loading security activity…</p> : securityEvents.length ? <div className="divide-y divide-white/10">{securityEvents.map((event) => <article key={event.id} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-white">{event.summary}</strong><time className="text-xs text-[#aeb9cd]">{new Date(event.createdAt).toLocaleString()}</time></div><p className="mt-1 text-[10px] font-bold uppercase tracking-[.1em] text-[#b8ff43]">{event.eventType.replaceAll("_", " ")}</p></article>)}</div> : <p className="p-5 text-sm text-[#aeb9cd]">No stored security activity is available yet.</p>}</section></div>}
      </div>
    </div>
  </section>;
}
