import { CheckCircle2, CirclePlus, Eye, Link2, Loader2, Search, ShieldCheck, Unlink, XCircle } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { MAPPING_ATTRIBUTE_LABELS, MAPPING_ATTRIBUTE_REQUIREMENTS, SUPPLIER_MAPPING_CATEGORIES, type SupplierMappingCategory } from "@shared/supplierProductMapping";
import { trpc } from "@/lib/trpc";
import "./adminSupplierProductMapping.css";

type MappingStatus = "UNMAPPED" | "PENDING REVIEW" | "APPROVED" | "REJECTED";
type Master = { id: number; name: string; category: SupplierMappingCategory; masterKey: string; regionLabel: string | null; currency: string | null; denomination: string | null; mappingAttributes: Record<string, string>; pendingOfferCount: number; approvedOfferCount: number };
type SupplierProduct = { id: number; supplierName: string; supplierProductId: string; name: string; category: SupplierMappingCategory; supplierCost: number | null; supplierCurrency: string | null; regionLabel: string | null; mappingStatus: MappingStatus; mappingOfferId: number | null; masterProductId: number | null; mappingAttributes: Record<string, string> | null };

const categoryLabel = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const blankAttributes = (category: SupplierMappingCategory) => Object.fromEntries(MAPPING_ATTRIBUTE_REQUIREMENTS[category].map((key) => [key, ""]));

export function AdminSupplierProductMapping() {
  const utils = trpc.useUtils();
  const summary = trpc.admin.getSupplierProductMappingSummary.useQuery(undefined, { refetchOnWindowFocus: true });
  const mastersQuery = trpc.admin.listSupplierProductMappingMasters.useQuery(undefined, { refetchOnWindowFocus: true });
  const [selectedMasterId, setSelectedMasterId] = useState<number | null>(null);
  const masterDetail = trpc.admin.getSupplierProductMappingMaster.useQuery({ masterProductId: selectedMasterId || 0 }, { enabled: Boolean(selectedMasterId) });
  const [searchText, setSearchText] = useState("");
  const [searchCategory, setSearchCategory] = useState<"all" | SupplierMappingCategory>("all");
  const searchInput = useMemo(() => ({ query: searchText.trim(), category: searchCategory === "all" ? undefined : searchCategory, limit: 30 }), [searchText, searchCategory]);
  const supplierSearch = trpc.admin.searchSupplierProductsForMapping.useQuery(searchInput, { enabled: searchText.trim().length >= 2 });
  const [notice, setNotice] = useState<string | null>(null);
  const [showMasterForm, setShowMasterForm] = useState(false);
  const [masterDraft, setMasterDraft] = useState({ name: "", category: "top_up" as SupplierMappingCategory, subcategory: "", productType: "", regionLabel: "", currency: "USD", denomination: "", imageUrl: "", mappingAttributes: blankAttributes("top_up") });
  const [offerDraft, setOfferDraft] = useState<{ product: SupplierProduct; attributes: Record<string, string>; note: string } | null>(null);

  const refresh = async () => {
    await Promise.all([
      utils.admin.getSupplierProductMappingSummary.invalidate(),
      utils.admin.listSupplierProductMappingMasters.invalidate(),
      utils.admin.getSupplierProductMappingMaster.invalidate(),
      utils.admin.searchSupplierProductsForMapping.invalidate(),
    ]);
  };
  const createMaster = trpc.admin.createSupplierProductMappingMaster.useMutation({ onSuccess: async (master) => { setNotice("Draft Master Product created. It is not customer-facing and has no supplier offers until you explicitly submit them for review."); setShowMasterForm(false); setSelectedMasterId(master.id); await refresh(); }, onError: (error) => setNotice(error.message) });
  const addOffer = trpc.admin.addSupplierOfferToMasterForReview.useMutation({ onSuccess: async () => { setNotice("Supplier offer submitted as PENDING REVIEW. No legacy product, price, routing, or customer-facing catalog record was changed."); setOfferDraft(null); await refresh(); }, onError: (error) => setNotice(error.message) });
  const approve = trpc.admin.approveSupplierOfferMapping.useMutation({ onSuccess: async () => { setNotice("Mapping approved and audit logged. Supplier routing and customer prices remain unchanged."); await refresh(); }, onError: (error) => setNotice(error.message) });
  const reject = trpc.admin.rejectSupplierOfferMapping.useMutation({ onSuccess: async () => { setNotice("Mapping rejected. The supplier product remains unchanged and is separate from every Master Product."); await refresh(); }, onError: (error) => setNotice(error.message) });
  const remove = trpc.admin.removeSupplierOfferMapping.useMutation({ onSuccess: async () => { setNotice("Only the additive mapping snapshot was removed. The original supplier product remains unchanged."); await refresh(); }, onError: (error) => setNotice(error.message) });

  const selectedMaster = masterDetail.data as (Master & { supplierOffers: Array<{ id: number; supplierName: string; supplierProductId: string; supplierProductName: string; supplierCost: number | null; supplierCurrency: string | null; regionLabel: string | null; mappingStatus: MappingStatus; mappingAttributes: Record<string, string> }> }) | undefined;
  const masters = (mastersQuery.data ?? []) as unknown as Master[];
  const searchResults = (supplierSearch.data ?? []) as SupplierProduct[];
  const isMutating = createMaster.isPending || addOffer.isPending || approve.isPending || reject.isPending || remove.isPending;

  const submitMaster = (event: FormEvent) => {
    event.preventDefault();
    createMaster.mutate({ name: masterDraft.name, category: masterDraft.category, subcategory: masterDraft.subcategory || null, productType: masterDraft.productType || null, regionLabel: masterDraft.regionLabel || null, currency: masterDraft.currency || null, denomination: masterDraft.denomination || null, imageUrl: masterDraft.imageUrl || null, mappingAttributes: masterDraft.mappingAttributes });
  };
  const openOfferReview = (product: SupplierProduct) => {
    if (!selectedMaster) { setNotice("View a Master Product first, then add a supplier offer for category-safe review."); return; }
    if (product.category !== selectedMaster.category) { setNotice("Cross-category mappings are blocked. Select a Master Product in the exact same category."); return; }
    if (product.mappingStatus !== "UNMAPPED") { setNotice("This supplier product already has a mapping record. It must be removed before a new review can be created."); return; }
    setOfferDraft({ product, attributes: { ...selectedMaster.mappingAttributes }, note: "" });
  };
  const submitOffer = (event: FormEvent) => {
    event.preventDefault();
    if (!offerDraft || !selectedMaster) return;
    addOffer.mutate({ masterProductId: selectedMaster.id, legacyProductId: offerDraft.product.id, mappingAttributes: offerDraft.attributes, note: offerDraft.note || null });
  };
  const changeMasterCategory = (category: SupplierMappingCategory) => setMasterDraft((current) => ({ ...current, category, mappingAttributes: blankAttributes(category) }));

  return <section className="supplier-product-mapping" aria-label="Supplier Product Mapping">
    <header className="supplier-product-mapping-header"><div><span>SUPPLIER PRODUCT MAPPING</span><h2>Review before connecting offers</h2><p>Names are never enough. Review exact category-specific attributes before a supplier offer can be connected to one VAMNUX Master Product. Mapping does not alter legacy products, prices, routing, fulfilment, orders, or storefront behavior.</p></div><button type="button" className="admin-primary-action" onClick={() => setShowMasterForm((open) => !open)}><CirclePlus size={16} /> Create New Master Product</button></header>
    <section className="mapping-safety-note"><ShieldCheck size={18} /><div><strong>Manual owner review only</strong><p>Every legacy product has a traceable Supplier Offer snapshot. Records remain UNMAPPED or PENDING REVIEW until an exact, category-safe owner decision is made. Telegram Stars and Mobile Legends adapter candidates remain separate; no automatic matching exists in this workspace.</p></div></section>
    {notice && <div className="mapping-notice" role="status"><CheckCircle2 size={16} /><span>{notice}</span><button type="button" onClick={() => setNotice(null)} aria-label="Dismiss mapping message"><XCircle size={16} /></button></div>}
    <div className="mapping-summary-grid">{[
      ["Mapped products", summary.data?.mappedProductCount ?? 0, "approved"],
      ["Unmapped products", summary.data?.unmappedProductCount ?? "—", "unmapped"],
      ["Requiring Admin review", summary.data?.requiringAdminReviewCount ?? 0, "pending"],
      ["Approved mappings", summary.data?.approvedMappingCount ?? 0, "approved"],
      ["Rejected mappings", summary.data?.rejectedMappingCount ?? 0, "rejected"],
    ].map(([label, value, tone]) => <article key={String(label)} className={String(tone)}><small>{label}</small><strong>{String(value)}</strong></article>)}</div>
    {showMasterForm && <form className="mapping-master-form" onSubmit={submitMaster}><div className="mapping-form-heading"><div><span>CREATE DRAFT MASTER PRODUCT</span><h3>Verified identity attributes</h3><p>The Master Product remains a draft and is not customer-facing. These attributes are the exact values every future supplier offer must match.</p></div><button type="button" className="admin-secondary-action" onClick={() => setShowMasterForm(false)}>Cancel</button></div><div className="mapping-form-grid"><label>Master Product name<input value={masterDraft.name} onChange={(event) => setMasterDraft({ ...masterDraft, name: event.target.value })} required /></label><label>Category<select value={masterDraft.category} onChange={(event) => changeMasterCategory(event.target.value as SupplierMappingCategory)}>{SUPPLIER_MAPPING_CATEGORIES.map((category) => <option key={category} value={category}>{categoryLabel(category)}</option>)}</select></label><label>Product type <input value={masterDraft.productType} onChange={(event) => setMasterDraft({ ...masterDraft, productType: event.target.value })} /></label><label>Subcategory <input value={masterDraft.subcategory} onChange={(event) => setMasterDraft({ ...masterDraft, subcategory: event.target.value })} /></label><label>Region label <input value={masterDraft.regionLabel} onChange={(event) => setMasterDraft({ ...masterDraft, regionLabel: event.target.value })} /></label><label>Currency <input maxLength={3} value={masterDraft.currency} onChange={(event) => setMasterDraft({ ...masterDraft, currency: event.target.value.toUpperCase() })} /></label><label>Denomination <input value={masterDraft.denomination} onChange={(event) => setMasterDraft({ ...masterDraft, denomination: event.target.value })} /></label><label>Image URL <input type="url" value={masterDraft.imageUrl} onChange={(event) => setMasterDraft({ ...masterDraft, imageUrl: event.target.value })} /></label></div><div className="mapping-attributes"><h4>Required exact mapping attributes</h4><div>{MAPPING_ATTRIBUTE_REQUIREMENTS[masterDraft.category].map((key) => <label key={key}>{MAPPING_ATTRIBUTE_LABELS[key] || key}<input value={masterDraft.mappingAttributes[key] || ""} onChange={(event) => setMasterDraft({ ...masterDraft, mappingAttributes: { ...masterDraft.mappingAttributes, [key]: event.target.value } })} required /></label>)}</div></div><button type="submit" className="admin-primary-action" disabled={isMutating}><CirclePlus size={16} /> {createMaster.isPending ? "Creating…" : "Create draft Master Product"}</button></form>}
    <div className="mapping-workspace-grid"><section className="mapping-master-list"><div className="mapping-section-heading"><div><span>VIEW MASTER PRODUCT</span><h3>Master Products</h3></div><small>{summary.data?.masterProductCount ?? 0} created</small></div>{mastersQuery.isLoading ? <div className="admin-empty"><Loader2 className="spin" size={20} /><p>Loading Master Products…</p></div> : !masters.length ? <div className="mapping-empty"><Link2 size={22} /><strong>No Master Products yet</strong><p>Create one only after you have verified its category-specific identity attributes. No supplier product is created or mapped automatically.</p></div> : <div className="mapping-master-rows">{masters.map((master) => <button type="button" key={master.id} className={selectedMasterId === master.id ? "active" : ""} onClick={() => setSelectedMasterId(master.id)}><span>{categoryLabel(master.category)}</span><strong>{master.name}</strong><small>{master.approvedOfferCount} approved · {master.pendingOfferCount} pending</small></button>)}</div>}</section>
      <section className="mapping-detail"><div className="mapping-section-heading"><div><span>VIEW SUPPLIER OFFERS</span><h3>{selectedMaster ? selectedMaster.name : "Select a Master Product"}</h3></div>{selectedMaster && <small>{categoryLabel(selectedMaster.category)}</small>}</div>{masterDetail.isLoading && selectedMasterId ? <div className="admin-empty"><Loader2 className="spin" size={20} /><p>Loading supplier offers…</p></div> : !selectedMaster ? <div className="mapping-empty"><Eye size={22} /><strong>Choose a Master Product</strong><p>Its exact review attributes and connected supplier-offer snapshots will appear here.</p></div> : <><div className="mapping-identity"><span>Master key {selectedMaster.masterKey}</span><div>{Object.entries(selectedMaster.mappingAttributes).map(([key, value]) => <small key={key}>{MAPPING_ATTRIBUTE_LABELS[key] || key}: <strong>{value}</strong></small>)}</div></div><div className="mapping-offer-list">{!selectedMaster.supplierOffers.length ? <p className="mapping-empty-inline">No supplier offers have been submitted for review.</p> : selectedMaster.supplierOffers.map((offer) => <article key={offer.id}><div><span className={`mapping-status ${offer.mappingStatus.toLowerCase().replaceAll(" ", "-")}`}>{offer.mappingStatus}</span><strong>{offer.supplierProductName}</strong><small>{offer.supplierName} · Source ID {offer.supplierProductId} · {offer.supplierCost === null ? "Cost unavailable" : `${offer.supplierCurrency || "USD"} ${offer.supplierCost.toFixed(2)}`} · {offer.regionLabel || "Region not recorded"}</small></div><div className="mapping-offer-actions">{offer.mappingStatus === "PENDING REVIEW" && <><button type="button" className="admin-primary-action" disabled={isMutating} onClick={() => approve.mutate({ supplierOfferId: offer.id })}>Approve Mapping</button><button type="button" className="admin-danger-action" disabled={isMutating} onClick={() => reject.mutate({ supplierOfferId: offer.id })}>Reject Mapping</button></>}<button type="button" className="admin-secondary-action" disabled={isMutating} onClick={() => window.confirm("Remove only this additive mapping snapshot? The original supplier product will remain unchanged.") && remove.mutate({ supplierOfferId: offer.id })}><Unlink size={14} /> Remove Supplier Offer</button></div></article>)}</div></>}</section></div>
    <section className="mapping-search"><div className="mapping-section-heading"><div><span>SEARCH SUPPLIER PRODUCT</span><h3>Find existing supplier products</h3><p>Search is read-only. It cannot change a supplier product. Select a Master Product first to add a same-category UNMAPPED product for review.</p></div></div><div className="mapping-search-controls"><label><Search size={16} /><input type="search" value={searchText} onChange={(event) => setSearchText(event.target.value)} placeholder="Product name, supplier SKU, or supplier offer ID" /></label><select value={searchCategory} onChange={(event) => setSearchCategory(event.target.value as "all" | SupplierMappingCategory)}><option value="all">All categories</option>{SUPPLIER_MAPPING_CATEGORIES.map((category) => <option key={category} value={category}>{categoryLabel(category)}</option>)}</select></div>{searchText.trim().length < 2 ? <p className="mapping-search-hint">Enter at least two characters to search the existing supplier-normalised catalog. Similar names do not create a match.</p> : supplierSearch.isLoading ? <div className="admin-empty"><Loader2 className="spin" size={20} /><p>Searching existing supplier products…</p></div> : <div className="mapping-search-results">{!searchResults.length ? <p className="mapping-search-hint">No supplier products matched this search.</p> : searchResults.map((product) => <article key={product.id}><div><span className={`mapping-status ${product.mappingStatus.toLowerCase().replaceAll(" ", "-")}`}>{product.mappingStatus}</span><strong>{product.name}</strong><small>{product.supplierName} · Supplier product ID {product.supplierProductId} · {product.supplierCost === null ? "Cost unavailable" : `${product.supplierCurrency || "USD"} ${product.supplierCost.toFixed(2)}`} · {product.regionLabel || "Region not recorded"}</small></div><div>{product.mappingStatus === "UNMAPPED" ? <button type="button" className="admin-primary-action" onClick={() => openOfferReview(product)}>Add Supplier Offer</button> : product.mappingOfferId ? <button type="button" className="admin-secondary-action" disabled={isMutating} onClick={() => window.confirm("Remove only this additive mapping snapshot? The original supplier product will remain unchanged.") && remove.mutate({ supplierOfferId: product.mappingOfferId!})}><Unlink size={14} /> Remove mapping</button> : null}</div></article>)}</div>}</section>
    {offerDraft && selectedMaster && <form className="mapping-offer-form" onSubmit={submitOffer}><div className="mapping-form-heading"><div><span>ADD SUPPLIER OFFER · PENDING REVIEW</span><h3>{offerDraft.product.name}</h3><p>{offerDraft.product.supplierName} · Source ID {offerDraft.product.supplierProductId}. Confirm the exact values below against source documentation before submitting.</p></div><button type="button" className="admin-secondary-action" onClick={() => setOfferDraft(null)}>Cancel</button></div><div className="mapping-attributes"><h4>Must exactly match {selectedMaster.name}</h4><div>{MAPPING_ATTRIBUTE_REQUIREMENTS[selectedMaster.category].map((key) => <label key={key}>{MAPPING_ATTRIBUTE_LABELS[key] || key}<input value={offerDraft.attributes[key] || ""} onChange={(event) => setOfferDraft({ ...offerDraft, attributes: { ...offerDraft.attributes, [key]: event.target.value } })} required /></label>)}</div></div><label className="mapping-note">Review note <textarea value={offerDraft.note} onChange={(event) => setOfferDraft({ ...offerDraft, note: event.target.value })} maxLength={1000} placeholder="Optional verification evidence or review note. Never include credentials." /></label><button type="submit" className="admin-primary-action" disabled={isMutating}><Link2 size={16} /> {addOffer.isPending ? "Submitting…" : "Submit for Admin review"}</button></form>}
    <footer className="mapping-boundary"><ShieldCheck size={16} /> <span>This workspace never automatically maps offers, changes existing product rows or IDs, exposes credentials, changes supplier routing or pricing, or changes customer-facing catalog behavior.</span></footer>
  </section>;
}
